### ISSUE TITLE
Extension not recognizing imports with .ts extension anymore

### ISSUE THREAD

**Issue by Zyrakia** [denoland/vscode_deno#147] opened 2020-08-15 13:18 UTC
**Describe the bug**
When I launched VSCode this morning to continue on my project, all the imports from the day before were suddenly not valid anymore. Nothing in my workspace has changed, and I don't remember updating anything.

Imports with .ts extensions, that Deno is supposed to accept, are not recognized anymore, the program still runs fine, but none of the type definitions or intellisense are there because it is not recognizing the import.

This is the same for remote and local modules, and as I said, it was working the day before, with me not having changed anything.

Deno is enabled in the workspace, I have tried enabling it globally aswell, which solved nothing.

**To Reproduce**
1. Open a TypeScript file in a Deno enabled workspace
2. Import a remote or local module with a .ts extension like Deno requires

**Expected behavior**
The import is recognized without error and all the type definitions and intellisense predictions are provided.

**Screenshots**
![image](https://user-images.githubusercontent.com/43284152/90313125-ee37ac80-debe-11ea-8f2b-a71f122267aa.png)

**Versions**
vscode: 1.48.0
deno: 1.3.0
extension: 2.0.10

**Comment by Zyrakia** [comment] 2020-08-15 13:23
Reverting to extension version 2.0.4 fixes this issue, but in any later version than that the issue persists.

**Comment by lucacasonato** [comment] 2020-08-15 13:27
Duplicate of #140. The fixed version should be released any minute now.

**Closed by lucacasonato** 2020-08-15 13:27 UTC

**Comment by Skillz4Killz** [comment] 2020-08-15 13:37
@lucacasonato Are you sure this is a duplicate of 140? I did not have any issues yesterday but I woke up today and am having this issue now where .ts error appears
![image](https://user-images.githubusercontent.com/23035000/90313470-de2dc600-deda-11ea-9f25-8bf08be73489.png)

**Comment by lucacasonato** [comment] 2020-08-15 13:42
Can you try with 2.0.13

**Comment by Zyrakia** [comment] 2020-08-15 13:44
> Can you try with 2.0.13

Issue is fixed for me in version 2.0.13.

**Comment by Skillz4Killz** [comment] 2020-08-15 13:44
Fixed in 2.0.13 You are right.
