### ISSUE TITLE
VSCode shows error at "import.meta.main"

### ISSUE THREAD

**Issue by joehillen** [denoland/vscode_deno#712] opened 2022-08-31 16:47 UTC
**Describe the bug**

When in vscode and `"typescript.tsserver.experimental.enableProjectDiagnostics": true,` is set, there is the following errors at `import.meta.main`:

```
The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.
Property 'main' does not exist on type 'ImportMeta'.
```

This happens with almost all extensions disabled except for Deno.

**To Reproduce**

1. `deno init`
2. `code .`
3. Add `"typescript.tsserver.experimental.enableProjectDiagnostics": true,` to `User/settings.json`
4. Run "Deno: Initialize Workspace"
5. Open `main.ts`

**Expected behavior**

Don't show an error.

**Versions**

vscode: 1.70.2 deno: 1.25.0 extension: 3.13.1

**Notes**

Obviously, the solution is to add `"typescript.tsserver.experimental.enableProjectDiagnostics": false,` to `.vscode/settings.json`, but it took me a while to find the culprit. Is there any way the Deno extension can prevent others from having this issue in the future?

**Comment by kitsonk** [comment] 2022-08-31 20:55
Duplicate of #437

**Closed by kitsonk** 2022-08-31 20:55 UTC
Labels: duplicate
