### ISSUE TITLE
Support config auto detection with enabled paths

### ISSUE THREAD

**Issue by kitsonk** [denoland/vscode_deno#713] opened 2022-09-13 21:23 UTC
Slightly related:
I have a config like so 
```
{
    "deno.enable": true,
    "deno.unstable": true,
    "deno.enablePaths": [
        "./api",
        "./webapp"
    ]
}
```
and configs in `./api/deno.jsonc` and `./webapp/deno.jsonc`. However, VS code doesn't seem to take the config into account, especially the import_map option, despite those folders being listed as "paths". I would expect each path to be considered its own Deno app with potentially a config of its own.

See Monorepo discussion: https://github.com/denoland/deno/discussions/9126#discussioncomment-3605938

_Originally posted by @eric-burel in https://github.com/denoland/vscode_deno/issues/701#issuecomment-1245152227_

**Comment by kitsonk** [comment] 2022-09-13 21:26
There are two issues here, one is "easy" the other is "hard":

1. When there is an enabled path, check there for config file auto detection versus the root of the workspace. (easy)
2. Support multiple config files in the same workspace. (hard) This is due to that there is only one instance of the Deno language server running, and that instance has a _configuration_.  We don't currently have the infrastructure to support multiple configurations in a single running language server and would be a fairly major re-architecture of how that works.  Desired, but diffcult.

**Comment by eric-burel** [comment] 2022-09-14 06:23
Thanks for opening a specific issue for this! So until this can be supported, I'll try to investigate how far I can go with just 1 config and import_map. After all, having just one file to manage is also a plus so it's worth it. I'll post updates on the "monorepo discussion" since this repo is specific to the VS Code extension: https://github.com/denoland/deno/discussions/9126#discussioncomment-3641455

**Comment by Leokuma** [comment] 2023-07-11 01:28
@bartlomieju This is fixed now. I just tested on Deno 1.35.0 and VSCode 1.80.0.

**Comment by niedzielski** [comment] 2023-07-16 18:16
This doesn't seem to work for me on Deno v1.35.1, Deno VSCode extension v3.19.1, VSCodium v1.80.1. I have [a pretty simple reproduction case here](https://github.com/niedzielski/vscode_deno-713) with this structure:

```
├── deno.json <-- I only know how to resolve std
├── root.test.ts
└── sub
    ├── deno.json <-- I know how to resolve esbuild_deno_loader
    └── sub.ts <-- I import esbuild_deno_loader
```

`deno run sub/sub.ts` runs in the CLI but opening sub.ts in VSCode shows typing errors for esbuild_deno_loader. I have the same issue with .ts files as with extensionless executable scripts. The root deno.json is always used but that doesn't have the same import map as the deno.json in the subdirectory.

**Comment by nayeemrmn** [comment] 2023-09-14 22:10
Closing in favour of #787.

**Closed by nayeemrmn** 2023-09-14 22:10 UTC
Labels: suggestion, configuration, maybe fix available
