### ISSUE TITLE
Plugin crashes constantly

### ISSUE THREAD

**Issue by itohatweb** [denoland/vscode_deno#343] opened 2021-02-22 18:33 UTC
**Describe the bug**
The plugin crashes constantly like every minute then nothing related to ts works anymore.

**To Reproduce**
I don't know how you can reproduce it. I use a windows machine with the newest deno version. And it just constantly crashes the only thing I do is coding.

**Expected behavior**
It should not crash.

**Versions**

vscode: 1.53.2
deno: 1.7.5
extension: 3.0.1

**Comment by lucacasonato** [comment] 2021-02-22 19:18
When it crashes, can you open the `Deno Language Server` logs in the `Output` panel of VS Code, and upload them here?

**Comment by hazae41** [comment] 2021-02-22 20:11
> Starting Deno language server...
  version: 1.7.4 (release, x86_64-pc-windows-msvc)
Connected to "Visual Studio Code" 1.53.2
language server initialized
Server ready.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', cli\lsp\tsc.rs:986:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: channel closed', cli\lsp\language_server.rs:877:66
[Info  - 21:09:19] Connection to server got closed. Server will restart.
[Error - 21:09:19] Request textDocument/hover failed.
Error: Connection got disposed.

**Comment by kitsonk** [comment] 2021-02-22 20:16
@hazae41 what happens when you upgrade to Deno 1.7.5? What does your `.vscode/settings.json` contain?

**Comment by hazae41** [comment] 2021-02-22 20:32
The problem seems gone when I updated Deno and reloaded my workspace 

The plugin didn't crash

Here are my settings 
> {
    "deno.enable": true,
    "deno.unstable": true,
    "deno.import_map": "./import_map.json",
    "deno.lint": true
}

**Comment by itohatweb** [comment] 2021-02-22 20:40
Gotta a new crash report here:
>Starting Deno language server...
  version: 1.7.5 (release, x86_64-pc-windows-msvc)
Connected to "Visual Studio Code" 1.53.2
language server initialized
Server ready.
[Error - 21:22:07] Request textDocument/codeAction failed.
  Message: The position is out of range.
  Code: -32602 

after this the extension stopped working

**Comment by kitsonk** [comment] 2021-02-22 20:41
@hazae41 Would you mind sharing your `import_map.json`?

**Comment by hazae41** [comment] 2021-02-22 20:44
It's an empty import map

> {
    "imports": {}
}

**Comment by kitsonk** [comment] 2021-02-22 20:44
@itohatweb I assume this occurred when you saved a document?

**Comment by kitsonk** [comment] 2021-02-22 20:48
@itohatweb while it isn't a fix and will look into it, try disabling the automatic application of code actions on save and see if it helps.

**Comment by itohatweb** [comment] 2021-02-22 22:32
Ok thank you I'll try this tomorrow.

**Comment by dashinja** [comment] 2021-02-25 05:06
Version 3.0.0 of the Deno Plugin works fine
![image](https://user-images.githubusercontent.com/25598950/109105599-47995780-76fc-11eb-9d4f-386b36c8d03d.png)

Upgrade to 3.0.01 of the Deno Plugin does not work fine
![image](https://user-images.githubusercontent.com/25598950/109105664-64358f80-76fc-11eb-92e2-22c45c7759c9.png)

Is this related? Problems may have begun after auto-upgrade of vscode deno extension, at least in my case.

**Comment by jamesliu96** [comment] 2021-02-26 08:50
Mine crashes as well.
It's probable that we're experiencing the same issue.

Environments (`deno --version`):
- deno 1.7.2 (release, x86_64-apple-darwin)
- v8 8.9.255.3
- typescript 4.1.3

`.vscode/settings.json`:
```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true
}
```

Steps to reproduce:
1. launch vscode with an existing deno project folder
2. open a `.ts` file in the editor (i.e., `mod.ts`)
3. find a deno built-in symbol (i.e., `Deno.Reader`)
4. Command⌘+click on the symbol
5. getting this prompt
![image](https://user-images.githubusercontent.com/2211002/109277358-2ea2ba80-7852-11eb-842e-27fe68144e35.png)
6. from now on, most hover tooltips, definitions and jumps become invalid

"Deno Language Server" output:
```text
Starting Deno language server...
  version: 1.7.2 (release, x86_64-apple-darwin)
Connected to "Visual Studio Code" 1.53.2
language server initialized
Server ready.
[Error - 4:45:54 PM] Request textDocument/documentHighlight failed.
  Message: An unexpected specifier (asset:///lib.deno.ns.d.ts) was provided.
  Code: -32602 
[Error - 4:45:54 PM] Request textDocument/hover failed.
  Message: An unexpected specifier (asset:///lib.deno.ns.d.ts) was provided.
  Code: -32602 
[Error - 4:46:00 PM] Request textDocument/hover failed.
  Message: An unexpected specifier (asset:///lib.deno.ns.d.ts) was provided.
  Code: -32602 
[Error - 4:46:00 PM] Request textDocument/hover failed.
  Message: An unexpected specifier (asset:///lib.deno.ns.d.ts) was provided.
  Code: -32602 
[Error - 4:46:01 PM] Request textDocument/definition failed.
  Message: An unexpected specifier (asset:///lib.deno.ns.d.ts) was provided.
  Code: -32602 
[Error - 4:46:02 PM] Request textDocument/definition failed.
  Message: An unexpected specifier (asset:///lib.deno.ns.d.ts) was provided.
  Code: -32602 
[Error - 4:46:05 PM] Request textDocument/definition failed.
  Message: An unexpected specifier (asset:///lib.deno.ns.d.ts) was provided.
  Code: -32602 
[Error - 4:46:08 PM] Request textDocument/definition failed.
  Message: An unexpected specifier (asset:///lib.deno.ns.d.ts) was provided.
  Code: -32602 
[Error - 4:46:17 PM] Request textDocument/hover failed.
  Message: An unexpected specifier (asset:///lib.deno.ns.d.ts) was provided.
  Code: -32602 

```

**Comment by lucacasonato** [comment] 2021-02-26 09:52
@jamesliu96 Please update to Deno 1.7.5

**Comment by kitsonk** [comment] 2021-04-06 01:39
@itohatweb I tried copying your settings and I didn't encounter any issues (though using v3.2.0 of the extension and Deno 1.8.3).

Are you still encountering the problem?

**Comment by martinmunillas** [comment] 2021-04-21 13:24
I'm having the same issue, this is the output: ```error: Found argument 'lsp' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
[Info  - 9:20:50 AM] Connection to server got closed. Server will restart.
error: Found argument 'lsp' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
[Info  - 9:20:50 AM] Connection to server got closed. Server will restart.
error: Found argument 'lsp' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
[Info  - 9:20:51 AM] Connection to server got closed. Server will restart.
error: Found argument 'lsp' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
[Info  - 9:20:51 AM] Connection to server got closed. Server will restart.
error: Found argument 'lsp' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
[Error - 9:20:51 AM] Connection to server got closed. Server will not be restarted.```

**Comment by satyarohith** [comment] 2021-04-21 13:40
@martinmunillas can you paste the output of `deno --version`? The current latest version of deno is `1.9.1`. And also provide the contents `.vscode/settings.json` and reproduction steps.

**Comment by martinmunillas** [comment] 2021-04-21 13:41
here is my settings.json

```
{
    "deno.enable": true,
    "deno.lint": true,
    "deno.unstable": true
}
```

i think is the version, thanks, for some reason i got 1.4.6

**Comment by martinmunillas** [comment] 2021-04-21 13:48
now with deno 1.9.1 and the settings in the comment above it still doesn't work and the output doesn't say much 

```
[Error - 9:47:29 AM] Starting client failed
Launching server using command deno failed.
```

**Comment by martinmunillas** [comment] 2021-04-21 13:49
with 1.9.1 works nice! :D

**Comment by itohatweb** [comment] 2021-05-06 17:00
Sorry for my late response, I'm on the newest version of the extension and it keeps stop working. Sometimes without reason sometimes with. Also after saving a file sometimes the plugin keeps trying to format the file but its just loading and never stops.

**Comment by GitHubJasper** [comment] 2021-05-11 07:57
I would like to bumb this.
Have the same issues, stops working for seemingly no reason (no error, etc.).

I think it is related to project size, as the number of files goes up the frequency of the freezes also seem to increase.

When it occurs the only fix is either force closing the deno process that vs code uses or reloading the window. It seems like the deno runtime just becomes clogged up after a certain amount of uses, and everything, including formatting, stops being responsive.

At this point I have tried everything, older versions of deno, reinstalling vs code/plugin, changing settings, even installed vs code insiders in the hope that would fix it.

**Comment by dannydenenberg** [comment] 2021-05-18 00:01
> @martinmunillas can you paste the output of `deno --version`? The current latest version of deno is `1.9.1`. And also provide the contents `.vscode/settings.json` and reproduction steps.

Upgrading to the **latest version** fixed it for me.

**Comment by GitHubJasper** [comment] 2021-05-18 08:25
I think that was a different issue from what @itohatweb  and I have.
Still glad it is fixed for you!


> I have noticed when I use prettier instead of the Deno auto formatter the plugin crashes less frequently.

Will try this, though it would be nice if we could just use deno fmt

**Comment by 11reed** [comment] 2021-07-10 19:23
I am having this issue every time I install the extension. 

`Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
[Info  - 3:20:21 PM] Connection to server got closed. Server will restart.
Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
[Info  - 3:20:21 PM] Connection to server got closed. Server will restart.
Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
[Info  - 3:20:21 PM] Connection to server got closed. Server will restart.
Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
[Info  - 3:20:21 PM] Connection to server got closed. Server will restart.
Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
[Error - 3:20:21 PM] Connection to server got closed. Server will not be restarted.`

**Comment by kitsonk** [comment] 2021-07-12 03:49
> I am having this issue every time I install the extension. I am using the latest version of Deno.
> 
> ```
> Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
> [Info  - 3:20:21 PM] Connection to server got closed. Server will restart.
> Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
> [Info  - 3:20:21 PM] Connection to server got closed. Server will restart.
> Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
> [Info  - 3:20:21 PM] Connection to server got closed. Server will restart.
> Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
> [Info  - 3:20:21 PM] Connection to server got closed. Server will restart.
> Cannot resolve module "file:///Users/user/Documents/projectl/lsp"
> [Error - 3:20:21 PM] Connection to server got closed. Server will not be restarted.
> ```

It sounds like vscode though is resolving to a really old version of Deno.  In the integrated console in vscode, what does `which deno` state and then what does that `deno version` output?

**Comment by kitsonk** [comment] 2021-07-19 23:25
There are various issues occurring here, with various root causes, some of the quite old.

I am closing the issue. If there are specific problems people are encountering, please open a new issue.

**Closed by kitsonk** 2021-07-19 23:25 UTC
Labels: needs info

**Comment by six-edge** [comment] 2022-12-08 22:18
I had this same error recently. The problem was that I installed the latest version of Deno in WSL2, however VS Code running under Windows still had a very old version of Deno installed. Once, I updated both the Windows and Linux binaries, everything worked perfectly 🚀
