### ISSUE TITLE
Is the debugging feature working?

### ISSUE THREAD

**Issue by jradxl** [denoland/vscode_deno#458] opened 2021-06-25 15:01 UTC
### test

**Describe the bug**
Use of Debugging does not work as per documentation, but I can get it to work as described below.
Ubuntu 21.04 (fully up to date, and reproduced in a newly installed Virtualbox instance)
vscode via deb package, 1.57.1
deno 1.11.2
plugin 3.6.1

**To Reproduce**
$cat main.ts
console.log("Hello, World!");
console.log("Hello, World!");
Deno.exit();  //<<< Needed to ensure the debugger does close correctly if/when a successful debug session is achieved.

1. Without launch.json (the Python Plugin works like this)
Using debug menu, using the Blue Run and Debug button, with and without breakpoint
Generally the debugger hangs and I get the dialog, Error processing Launch ....

2. With launch,json
A. No output unless a
      `"outputCapture": "std"`
or
     `"console": "integratedTerminal"`
is added

B: No breakpoint is hit if using
`--inspect`

C: Debugging only works if
`--inspect-brk`
is used, but of course, initial stop is on first line of code.

If I am doing something wrong, I don't know what it is!

**Expected behavior**
To work easily without launch.json, or with a correct launch.json automatically added using --inspect

**Versions**
Ubuntu 21.04 (fully up to date, and reproduced in a newly installed Virtualbox instance)
vscode via deb package, 1.57.1
deno 1.11.2
plugin 3.6.1

**Comment by zandaqo** [comment] 2021-06-29 10:12
The exact same situation since last May as I mentioned in #384, also went `--inspect-brk` in the meantime as a workaround.

**Comment by kitsonk** [comment] 2021-07-19 23:41
Duplicate of #384

**Closed by kitsonk** 2021-07-19 23:41 UTC
Labels: duplicate
