### ISSUE TITLE
Errors when editing a file

### ISSUE THREAD

**Issue by hazae41** [denoland/vscode_deno#373] opened 2021-03-17 16:30 UTC
I get the following error when I edit a file

```
Starting Deno language server...
  version: 1.8.1 (release, x86_64-pc-windows-msvc)
Connected to "Visual Studio Code" 1.54.3
language server initialized
Updating import map from: "import_map.json"
Server ready.
ERROR TSLS = Error: The current snapshot version is missing.
  Args: "GetChangeRangeArgs { specifier: "file:///.../mod.ts", old_length: 614, old_version: "1615998183203", version: "1615998410258" }"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:236:12)
    at ScriptSnapshot.getChangeRange (deno:cli/tsc/99_main_compiler.js:224:19)
    at acquireOrUpdateDocument (deno:cli/tsc/00_typescript.js:123008:133)
    at Object.updateDocumentWithKey (deno:cli/tsc/00_typescript.js:122974:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (deno:cli/tsc/00_typescript.js:149726:49)
    at tryReuseStructureFromOldProgram (deno:cli/tsc/00_typescript.js:107087:28)
    at Object.createProgram (deno:cli/tsc/00_typescript.js:106618:29)
    at synchronizeHostData (deno:cli/tsc/00_typescript.js:149648:26)
    at Object.getSuggestionDiagnostics (deno:cli/tsc/00_typescript.js:149784:13)
Unable to get document highlights from TypeScript: Error: The current snapshot version is missing.
  Args: "GetChangeRangeArgs { specifier: "file:///.../mod.ts", old_length: 614, old_version: "1615998183203", version: "1615998410258" }"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:236:12)
    at ScriptSnapshot.getChangeRange (deno:cli/tsc/99_main_compiler.js:224:19)
    at acquireOrUpdateDocument (deno:cli/tsc/00_typescript.js:123008:133)
    at Object.updateDocumentWithKey (deno:cli/tsc/00_typescript.js:122974:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (deno:cli/tsc/00_typescript.js:149726:49)
    at tryReuseStructureFromOldProgram (deno:cli/tsc/00_typescript.js:107087:28)
    at Object.createProgram (deno:cli/tsc/00_typescript.js:106618:29)
    at synchronizeHostData (deno:cli/tsc/00_typescript.js:149648:26)
    at Object.getDocumentHighlights (deno:cli/tsc/00_typescript.js:149890:13)
[Error - 17:26:50] Request textDocument/documentHighlight failed.
  Message: Internal error
  Code: -32603 
```

**Versions**

vscode: 1.54.3
deno: 1.8.1
extension: 3.2.0

**Comment by kitsonk** [comment] 2021-03-18 01:26
Duplicate of denoland/deno#9348 and is fixed by denoland/deno#9746 which is in the canary release and will be in Deno 1.8.2.

**Closed by kitsonk** 2021-03-18 01:26 UTC
Labels: duplicate
