### ISSUE TITLE
Local Import path not properly evaluated

### ISSUE THREAD

**Issue by UserJHansen** [denoland/vscode_deno#510] opened 2021-08-27 23:36 UTC
When local files are imported in vscode it gives me a deno(no-local) error.

I found the root cause of the error, it keeps chopping of the "C:" in the file path

# Example
 `import { WebSocketError } from "./errors.ts"`
Unable to load a local module: "file:///Users/⨌⨌⨌/GitHub/deno-websocket/errors.ts".
  Please check the file path.deno(no-local)

This is only while debugging in VSCode and does not affect the app while it's running

**Comment by kitsonk** [comment] 2021-08-28 05:11
Please provide the output from _View | Output_ and then the _Deno Language Server_ and the version of the extension you are using and the top output from _Deno: Language Server Status_ from the command palette.

**Comment by UserJHansen** [comment] 2021-08-29 01:21
# Output from Deno Language Server: 
Starting Deno language server...
  version: 1.13.1 (release, x86_64-pc-windows-msvc)
  executable: C:\ProgramData\chocolatey\lib\deno\deno.exe
Connected to "Visual Studio Code" 1.59.1
language server initialized
Server ready.

# Deno Server Status Output
## Deno Language Server Status
### Workspace Settings
`{
  "enable": true,
  "cache": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": false,
    "references": false,
    "referencesAllFunctions": false,
    "test": true
  },
  "internalDebug": false,
  "lint": true,
  "suggest": {
    "completeFunctionCalls": false,
    "names": true,
    "paths": true,
    "autoImports": true,
    "imports": {
      "autoDiscover": true,
      "hosts": {}
    }
  },
  "unstable": true
}`

**Comment by UserJHansen** [comment] 2021-08-29 01:28
I tested it and the issue stays even with unstable mode off

**Comment by kitsonk** [comment] 2021-08-29 07:23
Are you using WSL?

@dsherret any ideas?

**Comment by UserJHansen** [comment] 2021-08-30 01:59
I have WSL on the machine but haven't done any deno integration with it

**Comment by dsherret** [comment] 2021-08-31 18:53
I noticed the code is using deno-websocket so I tried reproducing the problem by debugging the server and client in the example folder. The import is resolving as suspected though on 1.13.2 (even while debugging and with the exact same workspace settings):

![image](https://user-images.githubusercontent.com/1609021/131559052-81c4d267-1cf2-4157-9591-c85c80c165f2.png)

@UserJHansen would you be able to provide some step by step instructions on what you did in the deno-websocket repo? Does this always happen for you?

**Comment by UserJHansen** [comment] 2021-09-01 01:14
I found and resolved the issue, somehow I was opening it from my users folder, don't know how that works.

I have been unable to reacreate this bug apart from using Ctrl+Shift+T to bring the tab back

Image of the bug:
![image](https://user-images.githubusercontent.com/47265397/131595607-1e543ee7-4a14-4221-a1a5-e3d3b7b0935b.png)
Instead of:
![image](https://user-images.githubusercontent.com/47265397/131595730-0c902d0a-5ff4-4c55-9c18-a921f293241b.png)

**Comment by kitsonk** [comment] 2021-09-01 01:50
`tsc` which is used internally in the language server when using things across drive letters... I don't know if that was a factor here, like if some of the files were on one drive and some on another?

**Comment by dsherret** [comment] 2021-09-01 01:52
I think we should look into this more. I'm going to reopen to see if I can reproduce tomorrow.

**Comment by UserJHansen** [comment] 2021-09-01 03:26
All the files are in the same folder on the main C:/ Drive

**Comment by bartlomieju** [comment] 2023-07-11 00:27
I believe this is now fixed, we're greatly improved handling of paths since this issue was reported. Please let me know if the problem persists.

**Closed by bartlomieju** 2023-07-11 00:27 UTC
Labels: needs investigation
