### ISSUE TITLE
Run file just hangs with no output

### ISSUE THREAD

**Issue by KotlinIsland** [denoland/vscode_deno#562] opened 2021-10-12 23:56 UTC
**Describe the bug**
running a file in vscode just seems to hang.
**To Reproduce**

1. press f5 and pick deno

**Expected behavior**
It runs

**Screenshots**

![image](https://user-images.githubusercontent.com/65446343/137042856-e75c53aa-ebe6-46f1-9876-03512e4adbaf.png)

In WSL, If I delete the entire deno cache folder then it runs once, but doesn't stop? is that intended?
![image](https://user-images.githubusercontent.com/65446343/137044254-2238c37d-90ae-4158-93cd-4eade2c55f8b.png)
this workaround doesn't seem to work in Windows.

**Versions**

vscode: 1.61.0 deno: 1.15.0 extension: 3.9.1

**Comment by kitsonk** [comment] 2021-10-13 00:40
Duplicate of #557

**Closed by kitsonk** 2021-10-13 00:40 UTC
Labels: duplicate
