### ISSUE TITLE
[Feature Request] Autocomplete in the import map

### ISSUE THREAD

**Issue by arnu515** [denoland/vscode_deno#697] opened 2022-07-17 15:49 UTC
Add autocomplete for https://deno.land/x or std urls in `import_map.json` files, like how it is in `import {} from "xxx"` in the regular ts/js files 

It's a QOL feature and I really think it's useful, maybe add a toggle for it in the settings?

Thanks

**Comment by kitsonk** [comment] 2022-07-17 23:43
Duplicate of denoland/deno#13621

**Closed by kitsonk** 2022-07-17 23:43 UTC
Labels: duplicate
