### ISSUE TITLE
deno-vscode formatter doesn't work with deno.json in the folder

### ISSUE THREAD

**Issue by raythurnevoid** [denoland/vscode_deno#1033] opened 2024-01-21 20:35 UTC
vscode can't format using deno's formatter if a `deno.json` or `deno.jsonc` file is in the folder

**To Reproduce**

Create a folder > `ctrl+shift+p` > Deno: Enable > create any ts file > create a deno.json file > `alt+shift+f` to format in the .ts file

**Expected behavior**

To format the file

**Versions**

deno 1.39.4 (release, x86_64-pc-windows-msvc)
v8 12.0.267.8
typescript 5.3.3
vscode 1.85
deno-vscode: 3.31.0

**Comment by unpin** [comment] 2024-01-22 17:48
I have been having the same problem ever since upgrading Deno to 1.39.3. I had to downgrade to 1.39.2 for now to make formatting work again.

**Comment by dsherret** [comment] 2024-01-25 02:14
Duplicate of https://github.com/denoland/vscode_deno/issues/1029

The fix is in 1.40, which is being released in a few hours.

**Closed by dsherret** 2024-01-25 02:14 UTC
