### ISSUE TITLE
Can't specify import map on a per workspace folder basis

### ISSUE THREAD

**Issue by khaled** [denoland/vscode_deno#726] opened 2022-10-05 17:39 UTC
I've got a workspace with multiple root folders in it.  They represent a couple different Deno projects, a couple of Node projects, and some other non-JS projects.  The Deno projects have different, separate import maps, yet I am unable to specify an import map at the folder level.  Only the following settings are available:

![Screen Shot 2022-10-05 at 1 35 52 PM](https://user-images.githubusercontent.com/11412/194125103-c950e87d-c6ff-4fe9-be18-e406d389bed8.png)

It appears to be possible to set import map only at the workspace level.

**To Reproduce**
1. Create a workspace and add multiple root Deno folders to it.
2. Go into VS code settings and select one of the folders
3. Look at Deno settings.

**Expected behavior**

I can set import maps at the root folder level.

**Versions**

vscode: 1.68.1 deno: 1.25.4 extension: 3.13.1

**Comment by kitsonk** [comment] 2022-10-06 00:00
At a fundamental level this is a duplicate of denoland/deno#14245.  It is a design limitation in that there is one configuration per running language server, and there is only one running language server per workspace, and the referenced issue would make varying the active configuration per workspace folder possible.  Challenge is it is not a small piece of work.

**Closed by kitsonk** 2022-10-06 00:00 UTC
Labels: duplicate
