### ISSUE TITLE
Handle `deno.json` or `import_map.json` as symbolic links

### ISSUE THREAD

**Issue by vwkd** [denoland/vscode_deno#784] opened 2023-01-03 18:49 UTC
**Is your feature request related to a problem? Please describe.**

Currently, it seems the extension can't handle if `deno.json` or `import_map.json` are symbolic links.

This might be a rare use case but occasionally useful if a framework hardcodes a dependency on `deno.json` or `import_map.json` and is put in a subdirectory, because then one create a symbolic link in the top-level directory such that the extension can work. For example, fresh has a hardcoded dependency on `deno.json` https://github.com/denoland/fresh/issues/961.

**Describe the solution you'd like**

Follow symbolic links.

**Comment by dsherret** [comment] 2023-07-20 21:18
> Describe the solution you'd like
>
> Follow symbolic links.

Just investigated this and symbolic links are not followed by design. When you have a deno.json as a symbolic link, then the base will be the link and not the destination.

> This might be a rare use case but occasionally useful if a framework hardcodes a dependency on deno.json or import_map.json and is put in a subdirectory, because then one create a symbolic link in the top-level directory such that the extension can work. For example, fresh has a hardcoded dependency on deno.json https://github.com/denoland/fresh/issues/961.

In this case, don't use symbolic links and instead use the "deno.config" option to specify the config in the sub directory. In the future, there will probably be workspaces and that might make the situation even easier.

That said, there was a bug where we weren't properly handling file changed events for these symlinked config files. I opened https://github.com/denoland/deno/pull/19898

**Comment by dsherret** [comment] 2023-07-20 21:20
Going to close this one, but an improvement will be made in https://github.com/denoland/deno/pull/19898

**Closed by dsherret** 2023-07-20 21:20 UTC
Labels: configuration, dx
