### ISSUE TITLE
Error when importing re-exported function

### ISSUE THREAD

**Issue by andrewbrey** [denoland/vscode_deno#781] opened 2022-12-30 20:14 UTC
When attempting to auto-import a function which is available from multiple files (the original file as well as another file in which it is re-exported), the LSP produces an error when you arrow through the suggested imports. See the minimal reproduction repository as well as the demo video to observe the behavior.

**Minimal Reproduction Repository**

https://github.com/andrewbrey/vscode_deno-lsp-import-error

**Expected behavior**

The LSP should not error when you arrow through the suggestions. It would also be _extremely helpful_ if the suggestions would list which file each export comes (in my demos, the reason is that I would prefer to always pull my imports from the "public api" of my code surfaced through the `mod.ts` ).

**Demo Video**

https://user-images.githubusercontent.com/34140052/210108288-e059b52e-7223-422e-a62a-6175a8ff5660.mp4

**Versions**

```
Deno Extension Version: v3.15.0
Published:              5/26/2020, 06:34:45
Last released:          12/14/2022, 06:04:18
Last updated:           12/29/2022, 13:52:27
Identifier:             denoland.vscode-deno

Deno Version: 1.29.1
deno --version
deno 1.29.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4

OS: Pop!_OS 22.04 LTS x86_64 (Linux)

VS Code Version: 1.74.2
```

**Comment by bartlomieju** [comment] 2022-12-31 13:46
Seems like a duplicate of https://github.com/denoland/deno/issues/15400

> The LSP should not error when you arrow through the suggestions. It would also be extremely helpful if the suggestions would list which file each export comes (in my demos, the reason is that I would prefer to always pull my imports from the "public api" of my code surfaced through the mod.ts ).

That's a good point, I believe default TS server can show that information, so we should look into adding it as well.

**Comment by andrewbrey** [comment] 2022-12-31 15:09
Ah great, glad it's already on the radar, and my apologies that I didn't see the referenced issue when I searched through looking if this was already reported.

As for the inclusion of "suggestion source file name", (a) yes, the default TS Server includes this and I think it's very helpful, and (b) should I make a second issue for it specifically?

Cheers, and thank you for your work on Deno!

**Comment by bartlomieju** [comment] 2023-01-02 23:12
> Ah great, glad it's already on the radar, and my apologies that I didn't see the referenced issue when I searched through looking if this was already reported.

No worries!

> As for the inclusion of "suggestion source file name", (a) yes, the default TS Server includes this and I think it's very helpful, and (b) should I make a second issue for it specifically?
>
> Cheers, and thank you for your work on Deno!

Another issue would be helpful, thanks!

**Comment by andrewbrey** [comment] 2023-01-03 03:10
@bartlomieju  I have created https://github.com/denoland/vscode_deno/issues/783 to track the secondary feature request here! Thank you for taking a look!

**Closed** 2023-01-03 17:13 UTC
Labels: bug

**Comment by andrewbrey** [comment] 2023-01-05 17:45
I just tested against today's `1.29.2` release which included this fix and confirmed that the LSP error message is now suppressed - thanks for the speedy turn-around on this! Cheers!
