### ISSUE TITLE
Extension doesn't work (No intellisense)?

### ISSUE THREAD

**Issue by cooperate** [denoland/vscode_deno#289] opened 2020-12-24 07:48 UTC
Followed directions on both canary and previous version and neither seem to work?

Workspace settings

```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"deno.enable": true
	}
}
```

Image of index.ts file:
[https://imgur.com/a/9YXGRLJ](url)

**Comment by kitsonk** [comment] 2020-12-24 10:15
For the canary release, what  version of Deno do you have installed? What does the Deno Language Server log say in Output tab of the integrated terminal in vscode?

Also, typically workspace settings in vscode go in `.vscode/settings.json` and look like this:

```js
 {
  "deno.enable": false
}
```

**Comment by cooperate** [comment] 2021-01-02 18:46
```
Starting Deno language server...
  version: 1.6.2 (release, x86_64-pc-windows-msvc)
Connected to "vscode" 1.52.1
language server initialized
Server ready.
```

**Comment by cooperate** [comment] 2021-01-02 19:12
Also, I have no `Deno: Init` option after installing the canary plugin.

https://i.imgur.com/rTx4MkM.png

**Comment by kitsonk** [comment] 2021-01-03 22:01
> Also, I have no `Deno: Init` option after installing the canary plugin.

Correct, that is not yet in the canary release.

I understand the problem, currently the Deno LSP does not support workspace folders (it is tracked here: https://github.com/denoland/deno/issues/8643).

**Comment by lucacasonato** [comment] 2021-02-19 16:45
Closing this as the issue is tracked in  denoland/deno#8643 and https://github.com/denoland/vscode_deno/issues/314

**Closed by lucacasonato** 2021-02-19 16:45 UTC
Labels: canary, enhancement, upstream
