### ISSUE TITLE
console.log output not shown

### ISSUE THREAD

**Issue by retog** [denoland/vscode_deno#423] opened 2021-05-30 14:54 UTC
**Describe the bug**

console log not shown

**To Reproduce**

1. go to debug console
2. enter `console.log("hello")`

**Expected behavior**

seeing "hello" somewhere

**Versions**

vscode: 1.56.2 deno 1.10.2 extension: 3.4.0

**Comment by kitsonk** [comment] 2021-05-31 00:07
Your steps to reproduce would "work as expected" as you haven't indicated what your debug configuration looks like (`.vscode/launch.json`) or that you actually started a debug session (`F5`/`Run | Start Debugging`), nor that you are at a breakpoint in your session (which is required to have the inspector interactive).

That being said, I do notice that `console.log("hello")` does not log to the inspector:

![colors_ts_—_oak](https://user-images.githubusercontent.com/1282577/120124456-e18b0780-c1f7-11eb-8ab6-2df9e589554a.png)

 @caspervonb @bartlomieju thoughts?

**Comment by caspervonb** [comment] 2021-05-31 09:45
Yeah we haven't implemented console messages in the inspector client yet.

https://github.com/denoland/deno/issues/4502
https://github.com/denoland/deno/issues/7866

**Comment by kitsonk** [comment] 2021-05-31 11:12
> This pane connects via the devtools protocol right?

Correct.

**Comment by kitsonk** [comment] 2021-05-31 11:26
Closing as duplicate of: denoland/deno#4502

**Closed by kitsonk** 2021-05-31 11:26 UTC
Labels: duplicate
