### ISSUE TITLE
Optionally use Docker image instead of local installation

### ISSUE THREAD

**Issue by halvardssm** [denoland/vscode_deno#435] opened 2021-06-06 10:32 UTC
**Is your feature request related to a problem? Please describe.**

As Deno now has an [official docker image](https://github.com/denoland/deno_docker), it would be great to add language support for VSCode without having to install Deno locally.

**Describe the solution you'd like**

Have an option for this extension to use the latest supported docker image instead of using the local installation.

**Comment by kitsonk** [comment] 2021-07-20 00:11
Effectively this is a duplicate of #415

**Closed by kitsonk** 2021-07-20 00:11 UTC
Labels: duplicate

**Comment by halvardssm** [comment] 2021-07-20 06:51
I would actually consider these two separate issues but connected. What this is a request for, is to add an option to use the docker image for lsp. This would mean that if this is enabled, the docker image will be downloaded and used automatically for lsp without any other configuration.

I used another vscode extension a while back which had exactly this feature. I’ll try to find it, and link it here later.
