### ISSUE TITLE
Linting in VS Code not working when using enableProjectDiagnostics

### ISSUE THREAD

**Issue by phifa** [denoland/vscode_deno#595] opened 2021-12-10 11:35 UTC
I set up a simple deno project with only this file. But the linting is messed up. It looks like the default TypeScript language server is still parsing this file, even though I have installed the extension.

```
import { cron } from 'https://deno.land/x/deno_cron@v1.0.0/cron.ts';
import { config } from 'https://deno.land/x/dotenv@v2.0.0/mod.ts';

console.log('cron initiated: ', new Date());

cron('*/5 * * * *', async () => {
  await fetch("bla")
});
```

My workspace settings: 

```
{
  "deno.lint": true,
  "deno.unstable": true,
  "deno.enable": true
}

```

<img width="759" alt="Bildschirmfoto 2021-12-10 um 11 33 20" src="https://user-images.githubusercontent.com/3061129/145567980-1a5095fb-2ad2-4b51-905d-1e483c159fe9.png">

<img width="794" alt="Bildschirmfoto 2021-12-10 um 11 32 20" src="https://user-images.githubusercontent.com/3061129/145567862-11cc3223-5b8e-45b1-9a1b-78076ad0368e.png">

<img width="793" alt="Bildschirmfoto 2021-12-10 um 11 32 51" src="https://user-images.githubusercontent.com/3061129/145567911-020c2e16-4e3e-424f-8a32-1b090a1e2829.png">

**Comment by kitsonk** [comment] 2021-12-16 21:57
I've moved the issue to vscode_deno, as built-in diagnostics appearing have nothing to do with the Deno CLI itself, but the suppression mechanism built into vscode_deno.

To be clear, these are environmental specific situations, where the supression mechanism is failing for a yet unidentified reason.  I had thought that maybe the next release of vscode was breaking something in a way, but @phifa indicates that it is broken in their environment irrespective of insiders.

So it is really hard to say "I have exactly the same issue, when will be fixed" because there are potentially many contributing reasons and we have been unable to replicate it and the detailed information provided by @phifa is not revealing anything we wouldn't expect to be true and works in other environments.

If @phifa you want to dig a bit deeper, it gets a bit complex, with a TypeScript/JavaScript file open for a Deno enabled project, under the command pallet, run _TypeScript: Open TS Server Log_.  Likely vscode will complain that the logging is not turned on.  Choose to enable it, and quit and restart vscode (or use _Developer: Reload Window_).  Once you have the log open, upload it somewhere and link to it in the issue.  There should be some diagnostic message in there related to what `typescript-deno-plugin` which might provide some insight, but also quite detailed information on what is going on inside the built-in TypeScript language service and why we might not be able to supress the messages.

The most logical guess is that there is some other TypeScript plugin that is modifying the built-in typescript in a way that we can't suppress the messages.

**Comment by phifa** [comment] 2021-12-17 10:51
So I did one thing, I restarted with extensions disabled, but it's the same thing: 

<img width="1440" alt="Bildschirmfoto 2021-12-17 um 10 43 46" src="https://user-images.githubusercontent.com/3061129/146532761-04bd6c80-45ac-421c-adb7-d4c41079d342.png">

**Comment by phifa** [comment] 2021-12-17 11:05
Here is the log @kitsonk 

https://www.codepile.net/pile/VpZaqWLW

**Comment by kitsonk** [comment] 2021-12-18 21:54
@phifa ok, that is interesting, basically the plugin that supresses the message from typescript is not being loaded or passed even.  For example this is from a working version:

```
Info 2    [20:25:39.801] Arguments: /vscode/bin/linux-x64/899d46d82c4c95423fb7e10e68eba52050e30ba3/node /vscode/bin/linux-x64/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/7f6409c00930ccae0b89/tscancellation-ef127da8994916ddd7e5.tmp* --logVerbosity verbose --logFile /home/vscode/.vscode-remote/data/logs/20211218T202533/exthost1/vscode.typescript-language-features/tsserver-log-ZQGIN1/tsserver.log --globalPlugins typescript-deno-plugin --pluginProbeLocations /home/vscode/.vscode-remote/extensions/denoland.vscode-deno-3.9.2 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
```

And here is from the log file you provided:

```
Info 2    [10:55:59.800] Arguments: /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /var/folders/t0/56bhgsk57zdf9kkfz7tqnz3h0000gn/T/vscode-typescript501/15058d5203ee10f255e9/tscancellation-384cdaac7fb7aded7049.tmp* --logVerbosity verbose --logFile /Users/phil/Library/Application Support/Code - Insiders/logs/20211217T103355/exthost1/vscode.typescript-language-features/tsserver-log-4Mu4XM/tsserver.log --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
```

You can see the following is missing:

```
--globalPlugins typescript-deno-plugin --pluginProbeLocations /home/vscode/.vscode-remote/extensions/denoland.vscode-deno-3.9.2
```

The extension registers itself with an API the vscode provides to load this plugin, and for some reason that seems to be going "wrong" in your environment.  I don't know if there are extension "trust" issues at play, or something else.  Are there any outputs in _Log (Window)_ or _Log (Extension Host)_ or _Extension_ indicating any errors.

I will investigate if we get any sort of signal in the extension that the plugin can't be loaded, and then surface that in the client, because ultimately the inability to load the plugin is what is causing the built-in diagnostics to not be supressed.

**Comment by phifa** [comment] 2021-12-20 10:15
wait. no, of course the plugin won't be loaded if I run vscode with ALL extensions disabled. I will do some manual testing without extensions.

**Comment by phifa** [comment] 2021-12-20 11:51
@kitsonk so, now here is a new log output. VS Code with all extensions disabled, except deno: 

https://gist.github.com/phifa/4ca8945535409964640900c680caa248

Looks like this line `--globalPlugins typescript-deno-plugin` is in there.

**Comment by kitsonk** [comment] 2021-12-20 13:37
@phifa ok, it appears that for some reason, the configuration is not coming over for the plugin, which is why it isn't suppressing the diagnostics.  For example, something like this is missing from the file:

```
Info 102  [00:26:23.017] request:
    {"seq":4,"type":"request","command":"configurePlugin","arguments":{"pluginName":"typescript-deno-plugin","configuration":{"enable":true}}}}
```

We do that here:

https://github.com/denoland/vscode_deno/blob/5c6aaabaab56abd95d789e21a0c0a3cf9eb247ea/client/src/ts_api.ts#L34-L38

If that code would throw, it is supposed to complain with a popup giving the error message, which appears to not be working, so for some reason, that code is likely running but silently failing.  I am at a loss though as to what could cause this to fail.

**Comment by phifa** [comment] 2021-12-20 15:13
too bad, please let me know if I can assist further. I wonder how many people are having the same issue though. I wonder how we could crete a reproducable set up

**Comment by jespertheend** [comment] 2021-12-23 01:33
@phifa do you happen to have a `jsconfig.json` with `"checkJs": true` in your workspace?
I can reliably reproduce this with all extensions disabled except for Deno.

Here's a reduced test case: [deno_with_checkjs.zip](https://github.com/denoland/vscode_deno/files/7766085/deno_with_checkjs.zip)

**Comment by phifa** [comment] 2021-12-27 12:49
@jespertheend no, as you see above in the screenshot, no additional files: https://github.com/denoland/vscode_deno/issues/595#issuecomment-996623713

**Comment by jespertheend** [comment] 2021-12-27 13:04
Do you have project diagnostics enabled? (`typescript.tsserver.experimental.enableProjectDiagnostics`) That also seems to trigger it for me.

**Comment by phifa** [comment] 2021-12-27 13:13
@jespertheend YES! I think that might be it! @Namekkural maybe givve this a go!

**Comment by phifa** [comment] 2021-12-27 13:15
```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true,
  "typescript.tsserver.experimental.enableProjectDiagnostics": false,
}
```

This fixes it.

**Comment by Namekkural** [comment] 2021-12-27 14:32
Thank you for looking into it!
I have tried a jsconfig.json with the contents that @phifa suggested. 

Adding 

`{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true
}`

in the jsconfig.json instead of the workspace file fixes 
_"An async function or method in ES5/ES3 requires the 'Promise'"_ 
but not the error regarding the imports. 

Interestingly, adding or removing the line 
`  "typescript.tsserver.experimental.enableProjectDiagnostics": false,`
does not change anything.

**Comment by jespertheend** [comment] 2021-12-27 15:05
@Namekkural If you want the errors to disappear you have to make sure that both:
- `typescript.tsserver.experimental.enableProjectDiagnostics` is set to `false`
- **and** your project doesn't contain any `jsconfig.json` files.

The `Deno.enable` setting doesn't belong in your `jsconfig.json` file, but rather in `.vscode/settings.json`. Or you can globally disable project diagnostics from the vscode settings screen.

**Comment by phifa** [comment] 2022-02-25 20:06
anything we can do to help fixing the issue? i really want to keep my `enableProjectDiagnostics` turned on.

**Comment by kitsonk** [comment] 2022-02-25 20:45
Why do you want to turn it on for a Deno project?  It is not useful in that context.

**Comment by jespertheend** [comment] 2022-02-25 21:03
@kitsonk I like getting early warnings and errors as I am typing. The reason why I prefer enabling project diagnostics over not enabling it, is that changing a file might make errors show up in other files. With project diagnostics enabled, the folders containing errors turn red and you immediately know you've done something wrong.
This is useful if, for instance, you have a helper file that is being used by multiple entry points. Running `deno run a.js` might not give you any type errors after you have changed something in `shared.js`, but running `deno run b.js` might. And unless you have project diagnostics enabled, you won't know about mistakes like these until you actually run all entry points that use `shared.js`.

**Comment by kitsonk** [comment] 2022-02-26 02:57
Enabling project diagnostics for the built in TypeScript server does not enable the same feature for the Deno language server. If there is a desire for the same feature in the Deno language server, that would be a separate request.

This issue only covers the situation where someone has it enabled globally for the built in TypeScript language server, but has enabled Deno for a specifoc workspace. Currently the only workaround would be to disable the feature in the workspace, as it breaks the suppression mechanism of the Deno vscode extension.

**Comment by phifa** [comment] 2022-02-26 19:47
i cannot get it to work... It does not seem possible to have a workspace with one folder a deno project and another folder with a typescript project and enable project diagnostics only for the typescript project. i can only enable it globally.

**Comment by ahuigo** [comment] 2022-09-13 10:23
I don't have such problem.

@phifa Could you provide a full tiny reproduced repo example for the bad case?

**Comment by antonymott** [comment] 2022-10-26 14:43
Linting error not suppressed as of Oct 26, 2022, mentioned in [this Astro Deno SSR adapter issue](https://github.com/withastro/astro/issues/5194)

**Comment by nayeemrmn** [comment] 2023-09-15 02:27
Tracked in #437.

**Closed by nayeemrmn** 2023-09-15 02:27 UTC
Labels: bug, needs investigation, high priority, dx
