### ISSUE TITLE
cannot find name 'Deno'

### ISSUE THREAD

**Issue by itajaja** [denoland/vscode_deno#66] opened 2020-05-28 19:23 UTC
![image](https://user-images.githubusercontent.com/697647/83184189-13562380-a0f7-11ea-8a49-e04828dcba21.png)

imports seem to work correctly, deno seems to be running:

![image](https://user-images.githubusercontent.com/697647/83184252-2e289800-a0f7-11ea-92c1-429107ae777e.png)

I didn't change any settings. what am I missing?

**Comment by chenguzhen87** [comment] 2020-05-29 02:15
you can upgrade 
![image](https://user-images.githubusercontent.com/28331609/83213637-37684200-a195-11ea-94cf-a36c2d9867a9.png)

**Comment by chosa91** [comment] 2020-05-29 11:19
Same here...
![image](https://user-images.githubusercontent.com/8747662/83254287-d77e9500-a1ae-11ea-89a7-ea8061ad0c73.png)

Deno output:
```
Found deno, version:
deno: 1.0.2
v8: 8.4.300
typescript: 3.9.2
```

**Comment by VadimPDev** [comment] 2020-05-29 11:26
![Screenshot_41](https://user-images.githubusercontent.com/24318305/83254986-4e6c5b80-a1b8-11ea-9205-45c9fe24cb6d.png)
![Screenshot_40](https://user-images.githubusercontent.com/24318305/83254991-50361f00-a1b8-11ea-8c3a-5e15dd867fe3.png)

**Comment by itajaja** [comment] 2020-05-29 13:12
> you can upgrade

no, I am already using the latest version of the right plugin, not the deprecated one

**Comment by airclovis** [comment] 2020-05-29 22:21
I had the same issue and it looks like when I install the extension from vs marketplace the `typescript-deno-plugin` version running is v1.29.0 😕

I've pulled the repo and build it locally then I've installed the .vsix manually and now it's working and it's running `typescript-deno-plugin v1.31.0`. Not ideal but it's working (at least for me 😛)

**Comment by TTSKarlsson** [comment] 2020-05-30 14:37
Yes, this happens to me too, the denoland plugin doesn't work at all while the deprecated justjavac does.

**Comment by towertop** [comment] 2020-06-01 05:54
I encounter this issue on the latest VSCode 1.45.1 on Mac. And I just figured out and resolve the problem by upgrade the global tsc to latest 3.9.3 and config VSCode to use that version with "typescript.tsdk".

I guess that was due to the VSCode inline tsc 3.8.3 didn't work well with deno's plugin, while deno's inline one is 3.9.2.
 
![QQ20200601-115435](https://user-images.githubusercontent.com/1001699/83379976-61c53400-a40f-11ea-8b8b-ba3c6fe1667c.png)

Checkout this link https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions for the steps.

**Comment by TTSKarlsson** [comment] 2020-06-01 06:35
I'm using latest VSCode Insider which also uses latest Typescript 3.9.4, and the denoland version of the extension doesn't work anyway (No import and no Deno namespace, but deno in the status bar). Both deprecated versions of the extension works (justjavac and axetroy).

**Comment by ford04** [comment] 2020-06-01 15:24
Maybe [this answer](https://stackoverflow.com/a/62101596/5669456) is helpful for people, configuring Deno types in VS Code.

Currently, this is a working solution for me with the built-in TypeScript version of VS Code `1.45.1`. If you need to configure a custom workspace version, you need to do some more steps - take a look at the docs [here](https://github.com/justjavac/typescript-deno-plugin#configuration).

**Comment by gabrielgrover** [comment] 2020-06-04 16:27
I am seeing this issue too.  I tried all the above solutions to no avail.  I don't imagine this is intended behavior.

**Comment by andyvanee** [comment] 2020-06-04 23:23
> you can upgrade
> ![image](https://user-images.githubusercontent.com/28331609/83213637-37684200-a195-11ea-94cf-a36c2d9867a9.png)

I think a number of people misunderstood this comment. It turns out the **deprecated** deno plugin by justjavac actually has a newer release than the official plugin (this one) - it worked for me.

**Comment by gabrielgrover** [comment] 2020-06-05 04:53
Not sure I would say that the comment was misunderstood.  Seems pretty clear and it should probably be changed?

**Comment by itajaja** [comment] 2020-06-05 13:04
nope, I have the new one, still deno doesn't work: 
![image](https://user-images.githubusercontent.com/697647/83879378-8705bb00-a70b-11ea-871d-e8ae2e927b16.png)

**Comment by TTSKarlsson** [comment] 2020-06-05 13:16
@itajaja , That's the problem, the "new" one is old (1.24.0), and the deprecated is newer (1.34.0). In other words, the extension from denoland doesn't work yet, but the extension from justjavac does, but you'll get a annoying deprecation popup on startup.

**Comment by itajaja** [comment] 2020-06-05 13:41
I see, thanks for the clarification. well, since this is still the repo for the "new" one, the new one still has this bug that needs to be solved

**Comment by codematix** [comment] 2020-06-06 05:09
> @itajaja , That's the problem, the "new" one is old (1.24.0), and the deprecated is newer (1.34.0). In other words, the extension from denoland doesn't work yet, but the extension from justjavac does, but you'll get a annoying deprecation popup on startup.

So is there an expected timeline for the official plugin to issue an update?

**Comment by austinrivas** [comment] 2020-06-06 05:45
reverting to the deprecated plugin until this issue is resolved

**Comment by ry** [comment] 2020-06-06 20:29
Closed by https://github.com/denoland/vscode_deno/pull/77

**Closed by ry** 2020-06-06 20:29 UTC

**Comment by solarkraft** [comment] 2020-07-26 19:05
[Note](https://github.com/denoland/vscode_deno/pull/77#issuecomment-640177332) that you may have to reinstall the extension to get this fix (I did, even though I newly installed it).

**Comment by apple151947** [comment] 2020-10-13 08:14
Im  facing the same issue.  i installed latest **Deno 1.4.6** version and **denoland.vscode-deno** extension. What is solution to this error??

**Comment by ebebbington** [comment] 2020-10-13 11:01
@rshashik restart your ide - what have you tried so far?

**Comment by rshashik** [comment] 2020-10-13 17:39
> @rshashik restart your ide - what have you tried so far?

1) installed deno 1.4.6
2) installed denon v2.4.4
3) installed denoland.vscode-deno extension in my mac
4) created .vscode/settings.json file and set **"deno.enable": true**
5) created server.ts file
`import { Application } from "https://deno.land/x/oak/mod.ts";
import router from "./routes.ts";
const port = Deno.env.get("PORT") || 5000;

const app = new Application();

app.use(router.routes());
app.use(router.allowedMethods());

console.log(`Server running on port ${port}`);

await app.listen({ port: +port });`

Error in my vscode editor at Deno.env.get("PORT"): Cannot find name 'Deno'.ts(2304)
[https://github.com/rshashik/pdr.git](url)

**Comment by ebebbington** [comment] 2020-10-13 20:56
@rshashik did you restart your IDE? Can you check the extension is enabled? Can you check it’s the correct link (click the link in the readme)?

**Comment by tsaulic** [comment] 2020-10-28 02:35
@rshashik 
are you sure your `settings.json` is valid?
for me it works, same versions as you + `.vscode/settings.json`:
`{
    "deno.enable": true
}
`

after - restart IDE and it works (for me)

**Comment by esquevin** [comment] 2020-11-13 11:28
I'm also encountering this issue.

I can see that the deno extension is doing something, since as soon as I set it to `"deno.enable": false` in my settings.json I get the `An import path cannot end with a '.ts' extension. Consider importing [...] .ts(2691)`

But when I set `"deno.enable": true` those import errors disappear but I still have `Cannot find name 'Deno'`. Types seems to default to `any` everywhere, and development is a pain.

The very odd thing is that, sometime, and I've not been able to figure exactly how, through a combination of activating / deactivating the extension, changing code in my project, restarting the TS server, restarting the deno language server, it starts to work properly…

But whenever I leave vscode and come back to the project, its broken again :(

I've tried disabling most of my vscode extensions without success… The issue is there for me, and I think it's a nasty one to figure out if some people never experience it :/

**Comment by nitowa** [comment] 2020-11-22 10:58
Same issue as in the OP, plus it doesn't pick up on cached modules.
`deno info some_file.ts` correctly reports cached dependencies and their respective dependency trees. The scripts also run/bundle/install just as expected.

`Deno.something(...)` reports `Cannot find name 'Deno'.ts(2304)`
and 
`import { some_module } from 'some_url';` reports `Could not find module "some_url" locally.Deno Language Server(1005)`

Environment (An ubuntu vm basically set up from scratch just to test deno out): 
-Fresh ubuntu 20.04.1 installation.
-Fresh VSCode 1.15.1
-Fresh deno installation 1.4.6
-Deno extension 2.3.3

.vscode/settings.json:
```
{
    "deno.enable": true,
    "deno.unstable": false,
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
}
```

The extension is enabled in VSCode. The deprecated version (justjavac.vscode-deno) does not show the behavior for `Deno.something` but fails to pick up on the cached modules too.

**Comment by pierredewilde** [comment] 2020-11-26 23:24
If you still have errors like `Cannot find name 'Deno'. ts(2304)`, try the following:

`View > Command Palette... > deno: Init > Enable deno lint? Yes`

> Deno is now set up. You can enable and disable settings (like `--unstable`) in the `.vscode/settings.json` file. Before the extension will work you need to reload VS Code. 

Click on `Reload window`

`vscode/settings.json` will contain:
```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true
} 
```
If you still have errors like `Could not find module "https://deno.land/..." locally. Deno Language Server(1005)`, try the following:

`View > Command Palette... > deno: Restart Deno Language Server`

**Comment by nitowa** [comment] 2020-11-27 06:09
Thanks for the answer. Following the instructions, the second half worked great and vscode now correctly reports the modules as known. Unfortunately it is still unaware of the `Deno` namespace and reports the familiar error. I recorded the steps, just in case, and you can look at the behavior here: https://streamable.com/cz2fkl

**Comment by pierredewilde** [comment] 2020-11-27 08:47
@nitowa: are you sure `Deno` is correctly installed ? 

`$ deno info`
**DENO_DIR location**: "$HOME/.deno"
**Remote modules cache**: "$HOME/.deno/deps"
**TypeScript compiler cache**: "$HOME/.deno/gen"

`lib.deno.unstable.d.ts` should be found in `$HOME/.deno`, not in `$HOME/.cache/deno`. 
`Deno <version>` should be showed at lower right of VSCode status bar eg `TypeScript 4.1.2 Deno 1.5.4`.

Check your `$DENO_DIR` envvar which should be set to `$HOME/.deno`

BTW, in your video, there is an `Unexpected end of JSON input `error, probably in `tsconfig.json`.

HTH,
Pierre

**Comment by nitowa** [comment] 2020-11-27 08:55
The project I'm testing with is pretty much https://github.com/lampewebdev/deno-boilerplate unmodified.  Not sure where the unexpected end of JSON came from, but tsconfig.json just reports the error from the previous post (and fwiw is valid json).

`deno info` yields
DENO_DIR location: "$HOME/snap/deno/15/.cache/deno"
Remote modules cache: "$HOME/snap/deno/15/.cache/deno/deps"
TypeScript compiler cache: "$HOME/snap/deno/15/.cache/deno/gen"

`which deno`
/snap/bin/deno

`deno -V`
deno 1.4.6

`$DENO_DIR` was in fact not set at all, but even after manually setting it, the error persists. Deno was installed via snap

**Comment by pierredewilde** [comment] 2020-11-27 10:32
`Deno` (without version) in status bar indicates that deno executable cannot be found in path. 
Otherwise, `Deno <version>` is displayed in status bar.

`DENO-DIR` is used to locate both `lib.deno.d.ts` and `lib.deno.unstable.d.ts` files.
At start, those files will be created automatically. 

If `Cannot find name 'Deno'. ts(2304)` error persists, restart VSCode window.

**Comment by Moranilt** [comment] 2020-12-24 09:24
> If you still have errors like `Cannot find name 'Deno'. ts(2304)`, try the following:
> 
> `View > Command Palette... > deno: Init > Enable deno lint? Yes`
> 
> > Deno is now set up. You can enable and disable settings (like `--unstable`) in the `.vscode/settings.json` file. Before the extension will work you need to reload VS Code.
> 
> Click on `Reload window`
> 
> `vscode/settings.json` will contain:
> 
> ```
> {
>   "deno.enable": true,
>   "deno.lint": true,
>   "deno.unstable": true
> } 
> ```
> 
> If you still have errors like `Could not find module "https://deno.land/..." locally. Deno Language Server(1005)`, try the following:
> 
> `View > Command Palette... > deno: Restart Deno Language Server`

It works for me fine. Thank you!

**Comment by awkhad** [comment] 2021-03-07 13:03
i had the same issue what worked for me was to press Ctrl+Shit+p in VS Code then Type Deno in the search. And click Deno Initialize workspace

**Comment by JerryGreen** [comment] 2021-07-09 14:28
I did Ctrl+Shift+P -> Initialize Workspace Configuration, which created me `.vscode/settings.json`:

```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": false
}
```

But still the problem occurs:

![image](https://user-images.githubusercontent.com/13215662/125093217-8b10c300-e0eb-11eb-97c8-92d8176f8dff.png)

vscode-deno: v3.7.0
deno 1.11.5 (release, x86_64-pc-windows-msvc)
v8 9.1.269.35
typescript 4.3.2

**Comment by zanayr** [comment] 2021-07-18 04:48
> i had the same issue what worked for me was to press Ctrl+Shit+p in VS Code then Type Deno in the search. And click Deno Initialize workspace

This worked for me, after 2 hours of searching for a solution. Deno needs to get their extension in order... 🙄

**Comment by kitsonk** [comment] 2021-07-18 04:58
> > i had the same issue what worked for me was to press Ctrl+Shit+p in VS Code then Type Deno in the search. And click Deno Initialize workspace
> 
> This worked for me, after 2 hours of searching for a solution. Deno needs to get their extension in order... 🙄

The welcome page and instructions make it clear the this needs to be done, as very few people have every TypeScript project be a Deno one. Is there some way we could make these instructions clearer in order to "sort our extension out"?

**Comment by bbrefeld** [comment] 2021-07-22 07:26
I encountered this issue as well today.

For me the following two steps fixed it:

1. press Ctrl+Shift+p and choose 'Deno: Initialize Workspace' to initialize the workspace.
2. press Ctrl+Shift+p and choose 'Deno: Restart Language Server'.

Also running step 2 was the missing step for me.

**Comment by JerryGreen** [comment] 2021-07-22 07:32
> I encountered this issue as well today.
> 
> For me the following two steps fixed it:
> 
> 1. press Ctrl+Shift+p and choose 'Deno: Initialize Workspace' to initialize the workspace.
> 2. press Ctrl+Shift+p and choose 'Deno: Restart Language Server'.
> 
> Also running step 2 was the missing step for me.

Thanks but this doesn't help in my case. It seems there are various reasons why this might happen. In my case it's likely has something to do with OS Windows, but can't say for sure. For those who tried all the hints from this issue and nothing works, I recommend to proceed / add your details in this new issue, to help investigate the problem: #466

**Comment by stagas** [comment] 2021-08-09 09:11
If you are using a custom `tsconfig.json` with Deno and getting this message, the solution is to add `"deno.ns"` to `lib`:

```json
  "compilerOptions": {
    "lib": [
      "esnext",
      "dom",
      "deno.ns"
    ]
```

**Comment by Scionax** [comment] 2021-09-02 16:15
> 
> 
> If you are using a custom `tsconfig.json` with Deno and getting this message, the solution is to add `"deno.ns"` to `lib`:
> 
> ```json
>   "compilerOptions": {
>     "lib": [
>       "esnext",
>       "dom",
>       "deno.ns"
>     ]
> ```

I was having the same issue, and this is what actually finally solved it for me. Thank you!

**Comment by faeztgh** [comment] 2021-09-12 18:18
1- Install this extension : [here](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno).
2- Ctrl+Shift+P in your working directory.
3- Write this: Deno: Initialize Workspace Configuration.
4- Yes.
5- Yes.

Your welcome.

**Comment by o-az** [comment] 2022-04-21 05:01
why is it so hard to get deno setup going yikes

**Comment by BlackAsLight** [comment] 2022-07-17 05:00
> If you are using a custom `tsconfig.json` with Deno and getting this message, the solution is to add `"deno.ns"` to `lib`:
> 
> ```json
>   "compilerOptions": {
>     "lib": [
>       "esnext",
>       "dom",
>       "deno.ns"
>     ]
> ```

You are the true MVP. Everyone else be going in circles.
"Do X. X didn't work. Do X. X didn't work. *repeat*"

**Comment by kitsonk** [comment] 2022-07-17 05:21
Seeing a lot of people get tripped up on the `deno.ns` I opened denoland/deno#15222 which would at least try to provide better information on how to resolve the issue.

**Comment by spiffytech** [comment] 2022-11-16 01:39
I had this issue, which was caused by this line in my VS Code `settings.json`:

`"typescript.tsserver.experimental.enableProjectDiagnostics": true`

I diagnosed this by starting VS Code with a blank profile (`code --user-data-dir=/tmp/vscode .`) and seeing that Deno support worked, so I removed lines from my VS Code config until I found the culprit.

This also fixed the error `An import path cannot end with a '.ts' extension.`.

**Comment by jxjj** [comment] 2022-12-12 05:03
In case it helps anyone else: I had this issue because I disabled the built-in *TypeScript and JavaScript Language Features* plugin in vscode to use the [volar plugin's takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) for VueJS development.

Searching `@builtin TypeScript` and then enabling the `TypeScript and JavaScript Language Features`  plugin solved the issue for me.

**Comment by colorsofcode** [comment] 2023-01-30 20:01
Had the same issue, resolved it by enabling Deno Language Server.

Open settings (⌘ + . / Ctrl + .) and search for Deno:enable and active it either for the workspace or user profile.

**Comment by tristantreb** [comment] 2023-02-05 11:54
I solved this issue by installing and enabling the [Deno plugin on VS Code ](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno)

**Comment by shinebayar-g** [comment] 2023-02-08 21:06
Does it really work?

![image](https://user-images.githubusercontent.com/3091558/217650721-84ae48ee-4825-4f7e-84c0-9cdb400fc980.png)

`.vscode/settings.json`
```json
{
    "deno.enable": true,
    "deno.lint": true,
    "editor.formatOnSave": true,
    "[typescript]": {
        "editor.defaultFormatter": "denoland.vscode-deno"
    }
}
```

**Comment by bartlomieju** [comment] 2023-02-08 21:07
> Does it really work?
> 
> ![image](https://user-images.githubusercontent.com/3091558/217650721-84ae48ee-4825-4f7e-84c0-9cdb400fc980.png)
> 
> `.vscode/settings.json`
> 
> ```json
> {
>     "deno.enable": true,
>     "deno.lint": true,
>     "editor.formatOnSave": true,
>     "[typescript]": {
>         "editor.defaultFormatter": "denoland.vscode-deno"
>     }
> }
> ```

Do you have an import map that maps `constructs` to a fully qualified URL?

**Comment by shinebayar-g** [comment] 2023-02-08 21:08
> Do you have an import map that maps `constructs` to a fully qualified URL?

Oh sorry forgot to include deno config file.

`deno.jsonc`
```json
{
    "imports": {
        "cdk8s": "npm:cdk8s@2.6.43",
        "constructs": "npm:constructs@10.1.244"
    },
    "tasks": {
        "dev": "deno run --watch main.ts",
        "build": "deno run --allow-env --allow-write main.ts"
    },
    "fmt": {
        "options": {
            "indentWidth": 4,
            "lineWidth": 100,
            "singleQuote": true
        }
    }
}

```

**Comment by bartlomieju** [comment] 2023-02-08 21:21
Please open a separate issue about this problem. It requires more investigation. Make sure you are using latest Deno and VSCode extension.

**Comment by shinebayar-g** [comment] 2023-02-08 21:22
> I had this issue, which was caused by this line in my VS Code `settings.json`:
> 
> `"typescript.tsserver.experimental.enableProjectDiagnostics": true`
> 
> I diagnosed this by starting VS Code with a blank profile (`code --user-data-dir=/tmp/vscode .`) and seeing that Deno support worked, so I removed lines from my VS Code config until I found the culprit.
> 
> This also fixed the error `An import path cannot end with a '.ts' extension.`.

For some reason, removing wasn't enough, even it wasn't enabled in User settings. But explicitly disabling it in `.vscode/settings.json` worked.

```json
{
    "deno.enable": true,
    "deno.lint": true,
    "editor.formatOnSave": true,
    "[typescript]": {
        "editor.defaultFormatter": "denoland.vscode-deno"
    },
    "typescript.tsserver.experimental.enableProjectDiagnostics": false
}
```

sorry for the noise.

**Comment by sjc5** [comment] 2023-07-12 03:45
> > I had this issue, which was caused by this line in my VS Code `settings.json`:
> > `"typescript.tsserver.experimental.enableProjectDiagnostics": true`
> > I diagnosed this by starting VS Code with a blank profile (`code --user-data-dir=/tmp/vscode .`) and seeing that Deno support worked, so I removed lines from my VS Code config until I found the culprit.
> > This also fixed the error `An import path cannot end with a '.ts' extension.`.
> 
> For some reason, removing wasn't enough, even it wasn't enabled in User settings. But explicitly disabling it in `.vscode/settings.json` worked. Maybe we could mention this somewhere in the extension README?
> 
> ```json
> {
>     "deno.enable": true,
>     "deno.lint": true,
>     "editor.formatOnSave": true,
>     "[typescript]": {
>         "editor.defaultFormatter": "denoland.vscode-deno"
>     },
>     "typescript.tsserver.experimental.enableProjectDiagnostics": false
> }
> ```
> 
> sorry for the noise.

Not noise! This worked for me, worth a try for others. Wow, weird bug.

**Comment by activenode** [comment] 2023-10-25 10:40
I got the same problem though none of the above worked unfortunately.

**Comment by jhd4tmr** [comment] 2023-11-27 09:23
> I got the same problem though none of the above worked unfortunately.

same

**Comment by jhd4tmr** [comment] 2023-11-28 02:31
Some other situations can also lead to this issue, for example, if you are using the Volar extension. This can cause a conflict with the Deno extension, as Volar, to my knowledge, involves managing TypeScript. The management of TypeScript by both can lead to conflicts, and disabling the Volar extension should resolve the issue.

**Comment by joshpachner** [comment] 2023-11-29 06:49
I got the same issue. And i've tried all the recommended solutions. 
The weird thing is that it was finding the Deno, and then "randomly" mid coding today it stopped. 🤷‍♂️ 
It still runs successfully but VScode is telling me it cant find it and the red lines are driving me crazy lol

**Comment by dgreensp** [comment] 2023-12-01 20:25
@joshpachner Thank you for pointing out that a TypeScript file seemingly anywhere in your project can cause this.  In my case, I think it was an NPM package in Deno's cache, which I keep checked into my repository.

**Comment by JorensM** [comment] 2024-01-19 09:36
> I got the same issue. And i've tried all the recommended solutions. The weird thing is that it was finding the Deno, and then "randomly" mid coding today it stopped. 🤷‍♂️ It still runs successfully but VScode is telling me it cant find it and the red lines are driving me crazy lol
> 
> But putting `/// <reference lib="deno.ns" />` at the top of my file (index.ts) worked. Some other github issue talks about how certain libraries have a `/// <reference no-default-lib="true"/>` which then throws everything amuck

I was having this issue and your suggestion solved it, but I was also getting `cannot find name 'console'` when doing `console.log`, which is still there.

**Comment by cameronraysmith** [comment] 2024-03-14 23:36
The [civet extension](https://marketplace.visualstudio.com/items?itemName=DanielX.civet) produces errors such as `typescript(2307)` as opposed to `ts(2307)` that can be difficult to track down in the context of resolving the issue from the OP.

**Comment by anthonyg56** [comment] 2024-04-28 04:22
> > > I had this issue, which was caused by this line in my VS Code `settings.json`:
> > > `"typescript.tsserver.experimental.enableProjectDiagnostics": true`
> > > I diagnosed this by starting VS Code with a blank profile (`code --user-data-dir=/tmp/vscode .`) and seeing that Deno support worked, so I removed lines from my VS Code config until I found the culprit.
> > > This also fixed the error `An import path cannot end with a '.ts' extension.`.
> > 
> > 
> > For some reason, removing wasn't enough, even it wasn't enabled in User settings. But explicitly disabling it in `.vscode/settings.json` worked. Maybe we could mention this somewhere in the extension README?
> > ```json
> > {
> >     "deno.enable": true,
> >     "deno.lint": true,
> >     "editor.formatOnSave": true,
> >     "[typescript]": {
> >         "editor.defaultFormatter": "denoland.vscode-deno"
> >     },
> >     "typescript.tsserver.experimental.enableProjectDiagnostics": false
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sorry for the noise.
> 
> Not noise! This worked for me, worth a try for others. Wow, weird bug.

This worked for me!

**Comment by marcelarie** [comment] 2024-06-01 22:59
I still have this problem, I can't go to definition.

**Comment by kyleinaction** [comment] 2024-09-27 00:23
> I still have this problem, I can't go to definition.

I had this problem as well. I enabled deno in my local workspace but still VSCode was using it's internal typescript language server instead of deno. 

I opened up my User Settings JSON (can be found in the Command Pallet Shift+Cmd/Ctrl+P) and saw a kv called `"deno.enablePaths": []`. I don't desire to enable/disable deno in this way, so I simply removed it entirely and voila, VSCode is now using deno for typescript files in deno-enabled workspaces. Hope this helps.

**Comment by FunctionDJ** [comment] 2024-10-11 16:27
> I had this issue, which was caused by this line in my VS Code `settings.json`:
> 
> `"typescript.tsserver.experimental.enableProjectDiagnostics": true`
> 
> I diagnosed this by starting VS Code with a blank profile (`code --user-data-dir=/tmp/vscode .`) and seeing that Deno support worked, so I removed lines from my VS Code config until I found the culprit.
> 
> This also fixed the error `An import path cannot end with a '.ts' extension.`.

This worked for me. Too bad this option appears to be incompatible with Deno because i think it's very useful. It's fair that it's incompatible, given that it's an experimental feature. I hope the TS devs can get this stable soon so Deno is incentivised to support it.

**Comment by fearandesire** [comment] 2024-11-05 21:36
> > > I had this issue, which was caused by this line in my VS Code `settings.json`:
> > > `"typescript.tsserver.experimental.enableProjectDiagnostics": true`
> > > I diagnosed this by starting VS Code with a blank profile (`code --user-data-dir=/tmp/vscode .`) and seeing that Deno support worked, so I removed lines from my VS Code config until I found the culprit.
> > > This also fixed the error `An import path cannot end with a '.ts' extension.`.
> > 
> > 
> > For some reason, removing wasn't enough, even it wasn't enabled in User settings. But explicitly disabling it in `.vscode/settings.json` worked. Maybe we could mention this somewhere in the extension README?
> > ```json
> > {
> >     "deno.enable": true,
> >     "deno.lint": true,
> >     "editor.formatOnSave": true,
> >     "[typescript]": {
> >         "editor.defaultFormatter": "denoland.vscode-deno"
> >     },
> >     "typescript.tsserver.experimental.enableProjectDiagnostics": false
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sorry for the noise.
> 
> Not noise! This worked for me, worth a try for others. Wow, weird bug.

Just piling on, this worked for me as well.

**Comment by NidalGhonaim** [comment] 2025-05-02 19:00
For supabase edge functions adding:

```JSON
"deno.enablePaths": ["./supabase/functions"],
"deno.importMap": "./supabase/functions/import_map.json",
```
to `.vscode/settings.json` as mentioned in these docs: [#deno-support-in-subfolders](https://supabase.com/docs/guides/functions/local-development#deno-support-in-subfolders) helped.

**Comment by marcospgp** [comment] 2025-08-07 19:23
I just ran into this today, it seems that my project's `tsconfig.json` is conflicting with Deno. whenever it is present, restarting vscode's TS server causes the `Deno` global variable's type to no longer be recognized

**Comment by FunctionDJ** [comment] 2025-08-29 13:03
`enableProjectDiagnostics` might stop being marked as experimental (see microsoft/TypeScript#36664).

if that happens, we can ask Deno to support it.
