### ISSUE TITLE
Debugger with `--inspect` does not hit breakpoints in VS Code

### ISSUE THREAD

**Issue by GJZwiers** [denoland/vscode_deno#559] opened 2021-10-10 18:50 UTC
Steps to reproduce:

- Open a new Deno project in VS Code
- Go to Run and Debug (ctrl + shift + d) and select "create a launch.json file", select Deno
- Add a `main.ts` file with some code and a breakpoint somewhere
- Begin debugging by pressing F5

Expected behaviour: debugger halts at the breakpoint
Actual behaviour: debugger appears to load for a while, then idles

`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "request": "launch",
            "name": "Launch Program",
            "type": "pwa-node",
            "program": "${workspaceFolder}/main.ts",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "C:\\Users\\Me\\.deno\\bin\\deno.EXE",
            "runtimeArgs": [
                "run",
                "--unstable",
                "--inspect",
                "--allow-all"
            ],
            "attachSimplePort": 9229
        }
    ]
}
```

With `--inspect-brk` everything works fine though. Possibly related to https://github.com/denoland/deno/issues/9886? Although in my case it also occurs when debugging files that haven't been cached yet.

`deno --version`:
```
deno 1.14.2 (release, x86_64-pc-windows-msvc)
v8 9.4.146.16
typescript 4.4.2
```

`code --version`:
```
1.60.2
```

**Comment by kitsonk** [comment] 2021-10-15 00:51
Duplicate of #557

**Closed as completed by kitsonk** 2021-10-15 00:51 UTC
Labels: duplicate
