### ISSUE TITLE
Extension breaks "Organize Imports" functionality

### ISSUE THREAD

**Issue by kamenminkov** [denoland/vscode_deno#650] opened 2022-04-05 21:25 UTC
Issue Type: <b>Bug</b>

1. Have the Deno extension enabled
2. Have a TypeScript file with some unused imports
3. Invoke the "Organize Imports" (`editor.action.organizeImports`) command

Expected: unused imports are removed upon invocation of the command.

Actual result: nothing happens.

Extension version: 3.12.0
VS Code version: Code - Insiders 1.67.0-insider (345f572e37ca69dc143c9fecb5f851fba9fcce8c, 2022-04-05T10:43:52.479Z)
OS version: Windows_NT x64 10.0.22581
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (12.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kamenminkov** [comment] 2022-04-05 22:01
Reproduces with the stable version of VSCode as of now (`1.66.0`) too.

**Comment by phifa** [comment] 2022-04-25 09:42
yes having the same issue, can confirm on Mac OS. 

```
Version: 1.66.2 (Universal)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z (2 wks ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0
```

**Comment by ragrag** [comment] 2022-06-17 20:37
Any updates on this one? gets really frustrating

**Comment by kitsonk** [comment] 2022-09-29 04:22
Duplicate of denoland/deno#14173

This is something that needs to be implemented in the language server.

**Closed by kitsonk** 2022-09-29 04:22 UTC
