### ISSUE TITLE
Unable to resolve resource ("@" in URL replaced with "%40")

### ISSUE THREAD

**Issue by Juribiyan** [denoland/vscode_deno#998] opened 2023-11-28 16:04 UTC
The extension fails to resolve the URL of one particular module, namely [http_status](https://deno.land/x/http_status@v1.0.1). It's maybe worth mentioning that the module exports only a single Enum. When attempting to _Go to Definition_ it shows an error with the following text:

> The editor could not be opened due to an unexpected error: Unable to resolve resource https://deno.land/x/http_status%40v1.0.1/mod.ts

As you can see the problem seems to be with the "@" character which is percent-encoded.

**To Reproduce**

1. Import the module:
```typescript
import * as httpStatus from "httpStatus";
```

2. Use the module:
```typescript
const code:number = httpStatus.SEE_OTHER;
```

3. See the error tip:
> Property 'SEE_OTHER' does not exist on type 'typeof import("https://deno.land/x/http_status@v1.0.1/mod")'.

4. Point to `httpStatus`, make a right click and select "_Go to Definition_" and see the error:
> The editor could not be opened due to an unexpected error: Unable to resolve resource https://deno.land/x/http_status%40v1.0.1/mod.ts

**Expected behavior**

The module's URL should be resolved correctly.

**Versions**

vscode: 1.84.2 deno: 1.37.2 extension: v3.28.0

**Comment by nayeemrmn** [comment] 2024-10-21 20:40
URI transcoding bugs have been fixed and I can't reproduce this. Closing.

**Closed by nayeemrmn** 2024-10-21 20:40 UTC
