### ISSUE TITLE
How to configure test to run on non Deno.test()?

### ISSUE THREAD

**Issue by clemens-tolboom** [denoland/vscode_deno#606] opened 2022-01-11 13:39 UTC
**Is your feature request related to a problem? Please describe.**

I'd like to run tests like done in ie https://github.com/denoland/deno_std/blob/main/fs/walk_test.ts where `test_walk()` takes care of `setup` and `teardown`.

I'm not sure whether this is either a simple tasks.json thing or `problemMatcher: $deno-test` like we have for in editor Run Test | Debug

![deno-test-single-test](https://user-images.githubusercontent.com/371014/148952784-630270b0-7304-4fd1-a19b-5ee74404fcd9.png)

**Describe the solution you'd like**

As `test_walk()` is a user defined function name as match could be `test_*` or the responsibility of the user to enter valid values/patterns.

**Comment by KyleJune** [comment] 2022-01-11 13:48
> **Describe the solution you'd like**
> 
> As `test_walk()` is a user defined function name as match could be `test_*` or the responsibility of the user to enter valid values/patterns.

I think it would be better if that could work with other function names too rather than just those with the "test_" prefix, for example if you are using a wrapper around Deno.test for writing tests in describe/it blocks.

**Comment by clemens-tolboom** [comment] 2022-01-11 13:56
> writing tests in describe/it blocks

What does that mean :-)

I just learned `deno test --filter "value"` matches the

```
Deno.test({
    name: "value"
```

How does that work? I cannot find this code :-/

**Comment by KyleJune** [comment] 2022-01-11 14:06
This is an example I wrote. There are others out there. Other common JavaScript test runners use describe functions for grouping tests together and giving them shared setup/teardown with before after hooks. Then it functions for the actual individual test cases.

https://deno.land/x/test_suite@0.9.5#describeit

**Comment by clemens-tolboom** [comment] 2022-01-11 18:16
@KyleJune thanks for the pointer to describe/it example. I know see your 'wrapped' issue. Have you checked with `test_walk` too.

Do you know a pointer to my other question in https://github.com/denoland/vscode_deno/issues/606#issuecomment-1009988469 ?

**Comment by nayeemrmn** [comment] 2023-08-25 04:06
Duplicate of #572.

**Comment by bartlomieju** [comment] 2023-08-25 09:04
I'm gonna close it in favor of #572

**Closed by bartlomieju** 2023-08-25 09:04 UTC
Labels: documentation, testing
