### ISSUE TITLE
Extension spawns `deno` instances even if `"deno.enable"` isn't set 

### ISSUE THREAD

**Issue by Altair-Bueno** [denoland/vscode_deno#734] opened 2022-10-15 11:53 UTC
**Describe the bug**

Extension spawns `deno` instances in the background even if "deno.enable" isn't set

**To Reproduce**

1. Make sure to kill all `deno` and `vscode/codehelper` instances on your system
2. Open vscode on any empty folder

**Expected behavior**

Projects without "deno.enable" shouldn't spawn `deno` instances in the background

**Screenshots**

<img width="713" alt="Empty project" src="https://user-images.githubusercontent.com/67512202/195984868-af296ada-52de-40da-b8f3-61382d4305b1.png">

<img width="671" alt="Activity monitor" src="https://user-images.githubusercontent.com/67512202/195984805-d89d60f0-2bfc-4916-ab93-15ab95ff0063.png">

**Versions**

vscode: 1.72.2 deno: 1.26.1 extension: v3.13.1 os: macOS 12.6

**Comment by kitsonk** [comment] 2022-10-15 13:19
Duplicate of #459 

An explination of why this is the case is in that issue, but specifically: https://github.com/denoland/vscode_deno/issues/459#issuecomment-869078161

**Closed by kitsonk** 2022-10-15 13:19 UTC
Labels: duplicate
