### ISSUE TITLE
[completion] override class method generate literally `$0`

### ISSUE THREAD

**Issue by loynoir** [denoland/vscode_deno#721] opened 2022-10-01 02:25 UTC
**Describe the bug**
[completion] override class method generate literally `$0`

**To Reproduce**
Before tab completion
```ts
class Y extends X {
}
```

After tab completion
```ts
class Y extends X {
  override stop(): Promise<void> {
      $0
  }
}
```
That `$0` is a literally `$0`

**Expected behavior**

```ts
class Y extends X {
  override async stop(): Promise<void> {
      <cursor />
  }
}
```
By the way, if return type is `PromiseLike`, should generate `override async method` instead of `override method`

**Screenshots**

**Versions**

vscode: xxx deno: xxx extension: xxx

**Comment by kitsonk** [comment] 2022-10-01 07:47
Duplicate of denoland/deno#15367

**Closed by kitsonk** 2022-10-01 07:47 UTC
