### ISSUE TITLE
Deno process on Windows is still running after quiting VSCode

### ISSUE THREAD

**Issue by web2033** [denoland/vscode_deno#444] opened 2021-06-08 17:21 UTC
**Describe the bug**
When the extension is enabled I cannot delete a project folder after exiting VSCode (win 10)

**To Reproduce**

1. Open any project in VSCode (even not related to Deno)
2. Close VSCode
3. Try to delete the project folder
4. Running Deno process won't allow it (uses that folder)

Confirmed by disabling extension - no problem then;
and by manually stopping the Deno process and then deleting a folder.

**Expected behavior**

Close Deno process(es) after exiting VSCode

**Versions**

vscode: 1.56.2 deno: 1.10.3 extension: 3.6.1

**Comment by kitsonk** [comment] 2021-06-08 22:22
Duplicate of #374

**Closed by kitsonk** 2021-06-08 22:22 UTC
