### ISSUE TITLE
Deno plugin will mangle yaml

### ISSUE THREAD

**Issue by unacceptable** [denoland/vscode_deno#1186] opened 2024-10-20 17:33 UTC
**Describe the bug**

YAML will be mangled by the Deno plugin.  Removing the Deno plugin in VSCode resolves the issue.

**To Reproduce**

1. Install the deno plugin in vscode
2. Create a yaml file 
3. Save the file

**YAML IDE Settings**

```
  "[yaml]": {
    "editor.insertSpaces": true,
    "editor.tabSize": 2,
    "editor.defaultFormatter": null
  },
```

**Expected behavior**

I would expect nothing to happen or for the yaml indentation to be changed to conform with style guidelines.

**Screenshots**

Before Save: 
> ![Screenshot 2024-10-20 at 11 26 13 AM](https://github.com/user-attachments/assets/1ef9199d-d7ed-4cb3-9f33-65f0ac3cd1fe)

After Save: 
> ![Screenshot 2024-10-20 at 11 25 42 AM](https://github.com/user-attachments/assets/86124621-c9b9-4d1e-88a6-3f250f5ca1dd)

**Versions**

vscode: 1.94.2 deno: 1.43.3 extension: v3.42.0

**Comment by nayeemrmn** [comment] 2024-10-24 13:08
I can't reproduce on v2.0.2. Please run `deno upgrade` and comment here if it's still an issue. Closing for now.

**Closed by nayeemrmn** 2024-10-24 13:08 UTC
