### ISSUE TITLE
Import Map + Import Suggestions

### ISSUE THREAD

**Issue by JerryGreen** [denoland/vscode_deno#478] opened 2021-07-27 11:19 UTC
I created further import map file:

```
{
  "imports": {
    "std/": "https://deno.land/std@0.103.0/"
  }
}
```

And I'm trying to import from an endpoint, which (surprisingly) gives me these beautiful hints:

![image](https://user-images.githubusercontent.com/13215662/127143800-0788628a-4840-48d2-8a7d-a326daf02383.png)

❗ But if I use import path, the hints are no more working:

![image](https://user-images.githubusercontent.com/13215662/127144074-d63d1c85-9a98-49e4-8157-41f0541fb5e0.png)

My `settings.json`:

```json
{
  "deno.enable": true,
  "deno.unstable": true,
  "deno.importMap": "./import_map.json",
  "deno.suggest.imports.hosts": {
    "https://deno.land": true
  }
}
```

Versions:

deno 1.11.5 (release, x86_64-pc-windows-msvc)
v8 9.1.269.35
typescript 4.3.2
vscode-deno v3.7.0

**Comment by kitsonk** [comment] 2021-07-27 11:26
Duplicate of #260 and denoland/deno#10951

**Closed by kitsonk** 2021-07-27 11:26 UTC
