### ISSUE TITLE
TS Server fatal error: Debug Failure.

### ISSUE THREAD

**Issue by jeiea** [denoland/vscode_deno#223] opened 2020-09-20 20:47 UTC
**Describe the bug**
vscode intellisense start fails after 5 try of launching ts server.

**To Reproduce**

Open [this repo(jeiea/vscode-deno-issue)](https://github.com/jeiea/vscode-deno-issue) in vscode and open any .ts file.

Excerpted from the readme of the repo.
1. Set `deno.enable` to true in `settings.json`
2. Include empty directory like `"include": ["src"]` in `tsconfig.json`
3. Open .ts file in vscode editor

**Expected behavior**

intellisense should work

**Screenshots**

![image](https://user-images.githubusercontent.com/4188984/93721834-967f1600-fbcd-11ea-8518-a43b0532ad0c.png)

**Versions**

windows: 10.0.19041.508
vscode: 1.49.1
deno: 1.4.1
extension: deno 2.2.3

**Comment by lucacasonato** [comment] 2020-09-20 20:48
Duplicate of https://github.com/denoland/vscode_deno/issues/215

**Comment by jeiea** [comment] 2020-09-20 20:49
@lucacasonato  No. I found precondition includes tsconfig. That issue doesn't related to that, and stacktrace is slightly different.

**Closed by lucacasonato** 2020-09-20 20:48 UTC
