### ISSUE TITLE
Hybrid node-w-ts and Deno workspace setup?

### ISSUE THREAD

**Issue by jessekrubin** [denoland/vscode_deno#448] opened 2021-06-10 05:08 UTC
How would I set up a hybrid ts+node and Deno workspace? 

I have several repos that are ts + node but I have a growing number of build/util scripts that are written in ts for Deno. Could there be a shebang-y solution?

**Comment by kitsonk** [comment] 2021-06-10 05:21
Duplicate of #297 

See: https://github.com/denoland/vscode_deno/blob/main/docs/workspaceFolders.md

**Closed by kitsonk** 2021-06-10 05:21 UTC
Labels: duplicate
