### ISSUE TITLE
Typescript extension is not disabled

### ISSUE THREAD

**Issue by Timmmm** [denoland/vscode_deno#455] opened 2021-06-22 21:19 UTC
The readme claims that installing and activating the Deno extension will disable the built in Typescript extension, and I can see some code that tries to do that. Unfortunately it doesn't seem to work. I still see errors from `ts`. I have to manually set these settings to remove them.

```
  "typescript.validate.enable": false,
  "javascript.validate.enable": false,
```

Without those settings I see this:

![image](https://user-images.githubusercontent.com/376842/123000638-bb482a00-d3a7-11eb-9432-ef1895a873d8.png)

**Versions**

vscode: 1.57.0 deno: 1.10.3 extension: `master` as of 10 minutes ago (8c1005031805dcb01aa149272632b85b645bc776).

This is on Mac.

**Comment by Timmmm** [comment] 2021-06-22 21:22
By the way, perhaps it would be simpler if the `Initialise Workspace Configuration` option just set those options rather than trying to do whatever `typescript-deno-plugin` fails to do.

**Comment by lucacasonato** [comment] 2021-06-22 21:56
Can you try on the latest Deno version?

**Comment by Timmmm** [comment] 2021-06-23 11:02
Yep, it made no difference.

**Comment by TheCymaera** [comment] 2021-07-19 06:13
I'm experiencing the same issue. I'm also using `"typescript.validate.enable": false` and`"javascript.validate.enable": false`, but this does not silence duplicate identifier errors caused by the builtin type definitions.

<img width="1153" alt="Screenshot 2021-07-19 at 1 58 08 PM" src="https://user-images.githubusercontent.com/69355340/126110822-050599c5-4dbf-4fcc-89e1-806c93988af0.png">

**Comment by kitsonk** [comment] 2021-07-19 06:28
> I'm experiencing the same issue. I'm also using `"typescript.validate.enable": false` and`"javascript.validate.enable": false`, but this does not silence duplicate identifier errors caused by the builtin type definitions.
> 

What happens when you do `deno run entry.ts`, what diagnostics, if any are reported?

What does your `tsconfig.json`, `import.json` and `settings.json` look like?

**Comment by TheCymaera** [comment] 2021-07-19 07:15
It won't work if I run, as I'm using web APIs. `deno bundle ...`  works as expected.
I believe the issue is that "deno.ns" is included implicitly in "lib". In fact, I get "Value is not accepted" as an error if I include it.

settings.json
```
{
	"deno.enable": true,
	"deno.unstable": true,

	"deno.importMap": "./importmap.json",
	"deno.config": "./tsconfig.json",

	"typescript.validate.enable": false,
}
```

tsconfig.json
```
{
	"compilerOptions": {
		"rootDir": "typescript",
		/*"outDir": "javascript",*/
		"module": "ESNext",
		"target": "ES2020",
		
		"strictNullChecks": true,
		"alwaysStrict": true,

		"lib": ["ESNext","DOM"]
	}
}
```

importmap.json
```
{
	"imports": {
		"app": "./typescript/app.ts"
	}
}
```

**Comment by kitsonk** [comment] 2021-08-30 22:39
There were some recent changes that caused issues when starting up vscode certain ways that caused this problem.  Please update to the latest version of the extension, and see if the issue is still a problem.

**Comment by Timmmm** [comment] 2021-09-08 10:13
Yeah it is still an issue, sorry! Deno extension 3.8.1, Deno 1.13.2.

**Comment by scarf005** [comment] 2023-06-24 00:23
![image](https://github.com/denoland/vscode_deno/assets/54838975/239ef99b-0296-4316-9a9c-bb8e6e2a2991)

this behavior is still happening in Deno v3.19.1, Deno v1.34.3.

**Comment by bartlomieju** [comment] 2023-07-11 00:11
@scarf005 so in your case the default TypeScript server is running even though you have Deno extension enabled in the workspace?

**Comment by scarf005** [comment] 2023-07-11 00:47
@bartlomieju can't reproduce on w/ vscode 1.80 && deno 1.35.0, seems to work well.

**Comment by bartlomieju** [comment] 2023-07-11 00:50
I'm gonna close this issue for now, since there are several issues similar to this one. Please let me know if you hit the problem again.

**Closed by bartlomieju** 2023-07-11 00:50 UTC
Labels: needs investigation, high priority, dx
