### ISSUE TITLE
VScode JS IntelliSense

### ISSUE THREAD

**Issue by evilsquirrel404** [denoland/vscode_deno#71] opened 2020-05-30 20:26 UTC
this VS code extension has removed/disabled VS code built in IntelliSense for JS
ie. doc... no longer suggests document 
     querys.. no longer suggests querySelector .

**Comment by ford04** [comment] 2020-06-01 15:42
Yeah, also experience similar issues. Minimal reproduction:

foo.js:
```
export function foo(s, n) {
  return 42
}
```
foo.d.ts (silbing file):
```
export function foo(s: string, n: number): number
```
main.ts:
```
// leaving out @deno-types here, as only affects deno CLI
import { foo } from "./foo.js";

foo("bar", 1)
```
With deno extension disabled, `foo` has correct types. With enabled extension, type will be inferred `function foo(s: any, n: any): number` in VS Code IDE. 

VS Code 1.45.1, vscode-deno 1.24.0

**Comment by edenprojectde** [comment] 2020-06-08 12:00
This should be a high priority. 
It's not reasonable to have 2 Editor instances open to edit a JS file that has to be served.. 
No offense, just saying.
Trying to add a child tsconfig seems to make the TS compiler crash too.

**Comment by Slugbat** [comment] 2020-07-04 23:14
I would agree that this needs to be addressed. In it's current state you must not have this extension enabled if you are writing JavaScript / Typescript code.

Even if you configure the tsconfig.json it does not use the default ECMAScript libs - nor does it use them if specified, in fact this extension disables VSCodes default ability to use ECMAScript lib's? 

This extension seems to be broken at the absolute fundamental level in its current state, it disables VSCodes ability to use ECMAScript lib's. Worrying.

**Comment by lucacasonato** [comment] 2020-09-08 21:51
The default is now that the extension is disabled. You must manually enable it using `"deno.enable"` in a `.vscode/settings.json` file in your project folder.

**Closed by lucacasonato** 2020-09-08 21:51 UTC

**Comment by Pictor13** [comment] 2023-06-19 20:11
A not for devs passing by: if Intellisense doesn't work ensure you run `Deno: Restart Language Server` from VSCode palette.

If I do not do it manually every time I open VSCode, I get no automatic Intellisense.... 🙄
