### ISSUE TITLE
Conflict with DOM API autocomplete

### ISSUE THREAD

**Issue by lipd** [denoland/vscode_deno#104] opened 2020-07-06 12:19 UTC
When I enable this plugin, VSCode stop autocomplete DOM API.

<img width="394" alt="Screen Shot 2020-07-06 at 8 13 41 PM" src="https://user-images.githubusercontent.com/25012301/86592217-9c4d5e00-bfc5-11ea-8bda-c89a3674aa82.png">

But when I turn off this plugin or add a eslint config file, autocomplete works again.

<img width="610" alt="Screen Shot 2020-07-06 at 8 11 21 PM" src="https://user-images.githubusercontent.com/25012301/86592376-ecc4bb80-bfc5-11ea-993d-3f5036188596.png">

I think this is a bug that needs to be fixed.

**Comment by lucacasonato** [comment] 2020-07-07 16:33
This is not a bug - while the Deno extension is assumes you are working with Deno source code, which does not have the DOM API. If you are not working on Deno code you can disable the extension.

**Comment by filleduchaos** [comment] 2020-07-08 06:35
@lipd you can simply disable the extension globally and then specifically enable it in workspaces where you're working with Deno. It certainly would be nice for the extension to not blanket hijack plain JS files (which are in my humble opinion nearly 100% likely to not be part of a Deno project), but in the meantime this works.

**Comment by mekwall** [comment] 2020-07-19 06:44
Disabling the extension is not a viable solution in a monorepo that also includes the client-side code that shares code with the deno codebase.

**Comment by lucacasonato** [comment] 2020-09-08 22:18
This should be fixed now because the extension isn't enabled by default now. You need to manually enable it using "deno.enable" in `.vscode/settings.json` in your project folder.

**Closed by lucacasonato** 2020-09-08 22:18 UTC
Labels: bug
