### ISSUE TITLE
deno language server should not start when deno.enable is not set

### ISSUE THREAD

**Issue by jeiea** [denoland/vscode_deno#626] opened 2022-02-23 05:05 UTC
**Describe the bug**

I didn't set `deno.enable` but deno.exe is always executing with vscode.

**To Reproduce**

1. Open vscode
2. Change empty editor's language mode to typescript

**Expected behavior**

I think it shouldn't run.

**Screenshots**

<img width="515" alt="image" src="https://user-images.githubusercontent.com/4188984/155264103-4043da60-6b55-4b83-ada0-5f72f1646532.png">

**Versions**

vscode: 1.64.2 (system setup)
deno: 1.19.0
extension: 3.10.1

**Comment by kitsonk** [comment] 2022-02-23 07:30
Duplicate of #459

**Closed by kitsonk** 2022-02-23 07:30 UTC
Labels: duplicate
