### ISSUE TITLE
Typing import.meta crash the extension

### ISSUE THREAD

**Issue by codehz** [denoland/vscode_deno#434] opened 2021-06-04 07:49 UTC
### test

**Describe the bug**

Typing import.meta crash the extension..

**To Reproduce**

1. Enable deno extension
2. Typing `i` `m` `p` `o` `r` `t` `.` `m` in a ts file

**Expected behavior**

No crash (or just mute the annoy popup for that case)

**Screenshots**

(just crash log)
```
Unable to get completion info from TypeScript: TypeError: Cannot read property 'kind' of undefined
    at getRootDeclaration (deno:cli/tsc/00_typescript.js:16600:21)
    at Object.isCatchClauseVariableDeclarationOrBindingElement (deno:cli/tsc/00_typescript.js:14152:20)
    at getTypeOfVariableOrParameterOrPropertyWorker (deno:cli/tsc/00_typescript.js:51624:20)
    at getTypeOfVariableOrParameterOrProperty (deno:cli/tsc/00_typescript.js:51587:28)
    at getTypeOfSymbol (deno:cli/tsc/00_typescript.js:51930:24)
    at getTypeOfSymbolAtLocation (deno:cli/tsc/00_typescript.js:65150:20)
    at Object.getTypeOfSymbolAtLocation (deno:cli/tsc/00_typescript.js:44091:35)
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (deno:cli/tsc/00_typescript.js:131138:97)
    at deno:cli/tsc/00_typescript.js:120534:41
    at Object.runWithCancellationToken (deno:cli/tsc/00_typescript.js:44374:28)

Request completionItem/resolve failed.
  Message: Internal error
  Code: -32603 
```

**Versions**

vscode: 1.56.2 deno: 1.10.3 extension: 3.5.1

**Comment by lucacasonato** [comment] 2021-06-04 08:33
Duplicate of https://github.com/denoland/deno/issues/10641

**Closed by lucacasonato** 2021-06-04 08:33 UTC
