### ISSUE TITLE
Define indentation rule

### ISSUE THREAD

**Issue by d2weber** [denoland/vscode_deno#698] opened 2022-07-18 21:11 UTC
**Is your feature request related to a problem? Please describe.**

Formatting a file works fine for me, but when typing VS Code uses a different indentation than the formatter.
For example, when typing this: 
```
const f = () =>
```
And then hitting `Enter`, it indents the number of spaces which are specified in the "select indentation" in the bottom bar of vs code.
I tested it in a *.ts file. I have "editor.autoIndent": "full".

**Describe the solution you'd like**

Define a language rule to have conformant indentation while typing and when formatting.

**Comment by kitsonk** [comment] 2022-10-27 00:34
This is effectively a duplicate of https://github.com/denoland/deno/issues/16083. We should set the language server _user preferences_ based on the configuration of `deno fmt` if any and this would meet the requirement without needing to add additional editor settings.

**Closed by kitsonk** 2022-10-27 00:34 UTC
