### ISSUE TITLE
Go to references won't find all references unless some user documents are open

### ISSUE THREAD

**Issue by bxantus** [denoland/vscode_deno#499] opened 2021-08-23 10:37 UTC
**Describe the bug**
When using "Go to references", the extension (and deno) won't find all references, unless some user documents are open.

For example, if you have an interface in a file, let's say `places.ts`:
```ts
export interface Place {
   // ...
}
```
The Place interface can be imported from multiple files, but if only `places.ts` is open in vscode, no references will be shown.

This can lead to many mistakes, as if you trust the extension to  find all references, you may miss some user codes, while refactoring, etc.

It seems to me, that only open documents and files imported from those open documents are scanned by the language server, instead of parsing the whole workspace (or files specified from some config, like tsconfig.json)

**To Reproduce**

See the description above.

1. Create an interface in it's own file
2. Use the interface in at least two separate files
3. Try to find references, while none or only some of the user documents are open

**Expected behavior**

All references should be found, no matter which documents are open in the workspace.
I would argue that references from file outside of the workspace should be found as well (when you open a subfolder from a solution). 
At least it should work like the built-in typescript language support for node.js projects.

**Versions**

vscode: 1.59.1 deno: 1.13.1 extension: 3.8.0

**Comment by kitsonk** [comment] 2021-08-23 12:01
Duplicate of deneland/deno#11190

**Closed by kitsonk** 2021-08-23 12:01 UTC
Labels: duplicate
