### ISSUE TITLE
Extension can't distinguish between variables in one file and the other

### ISSUE THREAD

**Issue by grian32** [denoland/vscode_deno#540] opened 2021-09-14 15:12 UTC
First file, error after the second file was created:
![image](https://user-images.githubusercontent.com/54550982/133284310-aa693e10-6a1d-4da7-8cc0-47960203a4a1.png)

Second file, no error: 
![image](https://user-images.githubusercontent.com/54550982/133284259-1e539b4d-318d-4dfa-b503-15c039a2cc6e.png)

File tree:
![image](https://user-images.githubusercontent.com/54550982/133284338-04d7c620-3b41-437e-8b8d-c9003e45b056.png)

probably a tsc issue

**Comment by soffieprincess07** [comment] 2021-09-14 15:22
> First file, error after the second file was created:
> ![image](https://user-images.githubusercontent.com/54550982/133284310-aa693e10-6a1d-4da7-8cc0-47960203a4a1.png)
> 
> Second file, no error:
> ![image](https://user-images.githubusercontent.com/54550982/133284259-1e539b4d-318d-4dfa-b503-15c039a2cc6e.png)
> 
> File tree:
> ![image](https://user-images.githubusercontent.com/54550982/133284338-04d7c620-3b41-437e-8b8d-c9003e45b056.png)
> 
> probably a tsc issue

**Comment by soffieprincess07** [comment] 2021-09-14 15:22
> > First file, error after the second file was created:
> > ![image](https://user-images.githubusercontent.com/54550982/133284310-aa693e10-6a1d-4da7-8cc0-47960203a4a1.png)
> > Second file, no error:
> > ![image](https://user-images.githubusercontent.com/54550982/133284259-1e539b4d-318d-4dfa-b503-15c039a2cc6e.png)
> > File tree:
> > ![image](https://user-images.githubusercontent.com/54550982/133284338-04d7c620-3b41-437e-8b8d-c9003e45b056.png)
> > probably a tsc issue

**Comment by soffieprincess07** [comment] 2021-09-14 15:22
> First file, error after the second file was created:
> ![image](https://user-images.githubusercontent.com/54550982/133284310-aa693e10-6a1d-4da7-8cc0-47960203a4a1.png)
> 
> Second file, no error:
> ![image](https://user-images.githubusercontent.com/54550982/133284259-1e539b4d-318d-4dfa-b503-15c039a2cc6e.png)
> 
> File tree:
> ![image](https://user-images.githubusercontent.com/54550982/133284338-04d7c620-3b41-437e-8b8d-c9003e45b056.png)
> 
> probably a tsc issue

**Comment by kitsonk** [comment] 2021-09-14 23:13
This is "working as designed" and is a "feature" of TypeScript.  Your "modules" don't have an import or export, therefore TypeScript treats those as script files and therefore it assumes it is the same global scope.  To work around the issue add `export {}` to the modules if the don't have other import export statements.

**Comment by kitsonk** [comment] 2021-09-17 01:45
Closing as duplicate of denoland/deno#10484

**Closed by kitsonk** 2021-09-17 01:45 UTC
Labels: design limitation, working as designed
