### ISSUE TITLE
Entire Workspace is Treated as Deno Code Instead of Only One Part

### ISSUE THREAD

**Issue by jessiejs** [denoland/vscode_deno#881] opened 2023-07-18 16:13 UTC
**Describe the bug**

**To Reproduce**

1. Make a code-workspace with a backend and frontend folder
2. Frontend should use invalid deno code
3. Backend should use valid deno code but invalid node code
4. Add settings.json to backend to enable Deno
5. Frontend also treated as Deno.

**Expected behavior**

Frontend not treated as Deno.

**Comment by bartlomieju** [comment] 2023-07-26 22:40
This is a duplicate of #488. It's something we're working towards addressing.

**Closed by bartlomieju** 2023-07-26 22:40 UTC
