### ISSUE TITLE
formatter runs when deno.enable = false

### ISSUE THREAD

**Issue by kyeotic** [denoland/vscode_deno#193] opened 2020-09-08 14:54 UTC
**Describe the bug**

When `deno.enable` is set to `false` saving a javascript file still hangs trying to run the Deno formatter.

**To Reproduce**

1. Install Deno extension
2. Enable extension in VS Code
3. Set `"deno.enable": false` in User Settings
4. Make a change to a `.js` file
5. Save the file

**Expected behavior**

The file should save without any attempt to run the deno formatter

**Screenshots**

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/1187432/92492603-5d47ae80-f1a8-11ea-99fa-bfe318f1eacb.png">

**Versions**

Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

deno 1.3.3
v8 8.6.334
typescript 4.0.2
extension: 2.2.0

**Comment by CGQAQ** [comment] 2020-09-08 15:28
Duplicate of #187

**Comment by kyeotic** [comment] 2020-09-08 15:32
@CGQAQ That issues seems to have a larger scope than this one. As far as I can tell this isn't actually an issue with the Language Server, and I would be worried about closing this issue and having the other issue drop the minor point regarding it.

**Comment by CGQAQ** [comment] 2020-09-08 15:37
It's the issue that lsp currently will not enabling or disabling dynamically according to the config

**Comment by CGQAQ** [comment] 2020-09-08 15:39
> @CGQAQ That issues seems to have a larger scope than this one. As far as I can tell this isn't actually an issue with the Language Server, and I would be worried about closing this issue and having the other issue drop the minor point regarding it.

You could keeping the issue open, I will try to fix this tomorrow

**Comment by David-Else** [comment] 2020-09-08 16:57
@CGQAQ If you try and fix it, please make sure we can still use the formatter with:
```
"deno.enable": false,
```
and:
```
"editor.defaultFormatter": "denoland.vscode-deno"
```

**Comment by lucacasonato** [comment] 2020-09-08 21:34
`"deno.enable"` should be completely separate from code formatting via `denoland.vscode-deno`. Formatting should exclusively be controlled by `"editor.defaultFormatter"`. The extension should not override this option **ever**.

**Comment by CGQAQ** [comment] 2020-09-09 03:07
> `"deno.enable"` should be completely separate from code formatting via `denoland.vscode-deno`. Formatting should exclusively be controlled by `"editor.defaultFormatter"`. The extension should not override this option **ever**.

So if `defaultFormatter` is not `vscode-deno`, even `vscode-deno` is enabled, it should never take over and format the code, right?

**Comment by CGQAQ** [comment] 2020-09-09 03:37
@lucacasonato @David-Else @kyeotic 
![issue](https://user-images.githubusercontent.com/15936231/92551504-c0ad0b80-f290-11ea-9c7e-3f16b2e5dd22.gif)

**Comment by kyeotic** [comment] 2020-09-09 04:13
@CGQAQ You can see in the screenshot I posted that both the **default** and **javascript formatter** are set to prettier. I have never set the default formatter to deno. I just reimaged this machine last week, so I am quite confident that it has never had that setting. Even if I had set it in the past shouldn't the fact that its not set that way _now_ still mean that the extension is behaving improperly?

The only way I can stop the deno formatter is to disable the extension.

**Comment by CGQAQ** [comment] 2020-09-09 04:15
> @CGQAQ You can see in the screenshot I posted that both the **default** and **javascript formatter** are set to prettier. I have never set the default formatter to deno. I just reimaged this machine last week, so I am quite confident that it has never had that setting. Even if I had set it in the past shouldn't the fact that its not set that way _now_ still mean that the extension is behaving improperly?
> 
> The only way I can stop the deno formatter is to disable the extension.

If you did not set default formatter to deno, vscode will not even trigger `vscode-deno` extension to format your code

**Comment by kyeotic** [comment] 2020-09-09 04:16
What evidence would you accept that this is not the case? I have already provided a screenshot.

**Comment by CGQAQ** [comment] 2020-09-09 04:19
> What evidence would you accept that this is not the case? I have already provided a screenshot.

I debugged the code, [this function](https://github.com/denoland/vscode_deno/blob/00b1bd7f9522f4f9f3c9458748993197e6c2eac2/server/src/language/document_formatting.ts#L18) not run if I set the defaultFormatter to prettier

**Comment by kyeotic** [comment] 2020-09-09 04:20
I'm not sure what to tell you then. I tried removing every other setting and it still runs deno

![image](https://user-images.githubusercontent.com/1187432/92553928-0f1ec380-f219-11ea-9e0f-0fcf111c947b.png)

**Comment by CGQAQ** [comment] 2020-09-09 04:22
@kyeotic 
![image](https://user-images.githubusercontent.com/15936231/92554103-22707400-f297-11ea-91b1-42bdc22682cf.png) click that, and see what is the content of that

**Comment by kyeotic** [comment] 2020-09-09 04:23
It opens settings with this filter

![image](https://user-images.githubusercontent.com/1187432/92554181-95d3a080-f219-11ea-9b28-2545c826bf26.png)

**Comment by CGQAQ** [comment] 2020-09-09 04:25
@kyeotic Please show me your settings.json in your workspace root .vscode folder

**Comment by kyeotic** [comment] 2020-09-09 04:26
Its empty. I have no workspace settings.

**Comment by kyeotic** [comment] 2020-09-09 04:27
This doesn't happen if I set `"editor.formatOnSave": false` or disable the extension. If I re-enable them both it starts happening again.

Perhaps it isn't in that function but it is definitely caused by this extension.

**Comment by CGQAQ** [comment] 2020-09-09 04:36
@kyeotic I'm sorry, but I can't reproduce this bug
![issue 2](https://user-images.githubusercontent.com/15936231/92554863-ee964e00-f298-11ea-95b1-0f1a9cf8d574.gif)

**Comment by kyeotic** [comment] 2020-09-09 04:47
Ok, that was definitely part of the problem. I had disabled prettier while I was trying to figure out what was going on. Re-enabling it causes it to run instead of deno.

I'm still confused though, because if I comment those lines out entirely I still get deno trying to run as the formatter. What is causing it to be selected when _no formatter is defined_?

This may be a seperate issue, but I am also confused about why it hangs instead of actually formatting anything.

**Comment by kyeotic** [comment] 2020-09-09 04:47
Unrelated, but what are you using for those gif recordings with key capture? That's pretty dope!

**Comment by CGQAQ** [comment] 2020-09-09 04:49
The key capture feature is vsode-built in feature
capture app is LICEcap

**Comment by CGQAQ** [comment] 2020-09-09 04:51
> I'm still confused though, because if I comment those lines out entirely I still get deno trying to run as the formatter. What is causing it to be selected when _no formatter is defined_?
> 

that's vscode's problem, you should definitely open an issue on vscode repo.
I don't have permission to close the issue, please close it, thank you

**Closed** 2020-09-09 04:57 UTC
