### ISSUE TITLE
"Deno": Unknown word.

### ISSUE THREAD

**Issue by justdayan** [denoland/vscode_deno#93] opened 2020-06-19 08:24 UTC
Hi All,

For whatever reason, I have the extension installed on 2 separate machines and I can't get it to recognize the namespace Deno. Am I missing something?

I have this in .vscode/settings.json

{
  "deno.enable": true,
}

![Screen Shot 2020-06-19 at 4 22 21 AM](https://user-images.githubusercontent.com/566428/85112969-83cafe80-b1e4-11ea-9742-5942bf11c071.png)

**Comment by Flaque** [comment] 2020-06-23 18:09
Hey @justdayan, this is likely caused by the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension, not the Deno VS Code extension.

**Comment by jeroenptrs** [comment] 2020-07-02 11:17
Similar issue:
`Cannot find name 'Deno'`
![image](https://user-images.githubusercontent.com/19305608/86352501-2f089880-bc66-11ea-861a-88d271bb39d6.png)

settings.json:
```
{
  "deno.enable": true
}
```

**Comment by BentoumiTech** [comment] 2020-08-14 05:08
I'm having the same issue than @jeroenptrs but when using the deprecated vscode extensions everything works fine.

**Comment by lucacasonato** [comment] 2020-09-08 22:00
This should be fixed now. If you still encounter this error, please open a new issue.

**Closed by lucacasonato** 2020-09-08 22:00 UTC
Labels: bug

**Comment by jeroenptrs** [comment] 2020-09-09 08:03
@BentoumiTech should be resolved when setting deno.enable on your workspace instead of globally

**Comment by BentoumiTech** [comment] 2020-09-09 08:31
@jeroenptrs Thank I will try

**Comment by rvdende** [comment] 2020-10-04 18:33
If you've set deno.enable and it still says cannot find "Deno" then just restart vscode and it should work.
