### ISSUE TITLE
VSCode setting `updateImportsOnFileMove` is not working

### ISSUE THREAD

**Issue by italodeandra** [denoland/vscode_deno#692] opened 2022-07-07 13:39 UTC
**Describe the bug**

VSCode doesn't prompt me to update the imports on file move.

**To Reproduce**

1. Create a function
2. Import that function in another file
3. Move the file of the function somewhere else

**Expected behavior**

VSCode should prompt to update the imports.

![image](https://user-images.githubusercontent.com/19225266/177787895-eb8aacad-4263-4a49-9885-abe0cd97f630.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/19225266/177787204-5347e070-fda0-4508-af79-b79d5a91b94d.png)

**Versions**

vscode: `1.68.1` deno: `1.23.2` extension: `3.13.0`

**Comment by elliothimmelfarb** [comment] 2022-12-10 20:43
Bumping this, as this has been my biggest issue with using Deno so far.

**Comment by monkybrain** [comment] 2023-03-24 09:35
Hey! Any progress on this issue?

**Comment by rmnoon** [comment] 2023-05-01 22:20
I just ran into the same thing!

**Comment by bartlomieju** [comment] 2023-07-11 00:32
Possibly a duplicate of https://github.com/denoland/vscode_deno/issues/410

**Comment by bartlomieju** [comment] 2023-07-11 22:25
I'm gonna close this issue in favor of #410. Let's continue there.

**Closed by bartlomieju** 2023-07-11 22:25 UTC
Labels: duplicate, enhancement, needs investigation, high priority, dx
