### ISSUE TITLE
formatOnSave & autocomplete became slower after update with Deno 1.37.0

### ISSUE THREAD

**Issue by ynwd** [denoland/vscode_deno#931] opened 2023-09-21 09:44 UTC
**Describe the bug**

- `formatOnSave` and autocomplete became slower after update with Deno 1.37.0
- this did not happen in previous versions

what actually happened?

**Operating System**
- Mac

**Comment by ynwd** [comment] 2023-09-22 04:09
For a temporary solution, use [`esbenp.prettier-vscode`](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) again.

```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.codeLens.test": true,
  "editor.formatOnSave": true,
  "deno.importMap": "import_map.json",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[css]": {
    "editor.defaultFormatter": "vscode.css-language-features"
  }
}

```

**Comment by bartlomieju** [comment] 2023-09-22 09:20
CC @nayeemrmn can you take a look?

**Comment by ynwd** [comment] 2023-09-23 22:27
> For a temporary solution, use [`esbenp.prettier-vscode`](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) again.
> 
> ```json
> {
>   "deno.enable": true,
>   "deno.lint": true,
>   "deno.codeLens.test": true,
>   "editor.formatOnSave": true,
>   "deno.importMap": "import_map.json",
>   "editor.defaultFormatter": "esbenp.prettier-vscode",
>   "[typescriptreact]": {
>     "editor.defaultFormatter": "esbenp.prettier-vscode"
>   },
>   "[typescript]": {
>     "editor.defaultFormatter": "esbenp.prettier-vscode"
>   },
>   "[javascriptreact]": {
>     "editor.defaultFormatter": "esbenp.prettier-vscode"
>   },
>   "[javascript]": {
>     "editor.defaultFormatter": "esbenp.prettier-vscode"
>   },
>   "[css]": {
>     "editor.defaultFormatter": "vscode.css-language-features"
>   }
> }
> ```

It not works, btw.

So i downgrade to 1.36.4 -- and the problem is gone.

@bartlomieju @nayeemrmn

**Comment by nayeemrmn** [comment] 2023-09-23 23:00
@ynwd If the problem is still there when changing the default formatter, it's not the formatter that's slow. Is it just the LSP in general being unresponsive? I can't see anything like that. Can you give a more detailed reproduction e.g. a sample file in a new project?

**Comment by ynwd** [comment] 2023-09-24 01:32
> @ynwd If the problem is still there when changing the default formatter, it's not the formatter that's slow. Is it just the LSP in general being unresponsive? I can't see anything like that. Can you give a more detailed reproduction e.g. a sample file in a new project?

@nayeemrmn 
very strange. after re-downloading 1.37.0, the problem went away. I will reopen this issue if the problem occurs again. Thank You.

**Comment by nayeemrmn** [comment] 2023-09-24 03:53
@ynwd Looks like this is the same as https://github.com/denoland/deno/issues/20136. Watch that issue for updates.

**Comment by ynwd** [comment] 2023-09-24 06:33
on a very small  project (like hello world http server), this problem is not found.

but when I switch to the bigger one (with watch mode and a complex import_map -- fullstack apps),  this problem is found again.  

so my temporary solution is back to use previous version (v1.36.4)

**Comment by nayeemrmn** [comment] 2023-09-26 22:22
Closing in favour of #943. Thanks for reporting

**Closed by nayeemrmn** 2023-09-26 22:22 UTC
Labels: needs info
