### ISSUE TITLE
for a new project, initializing a workspace requires a restart of the language server

### ISSUE THREAD

**Issue by yilmazdurmaz** [denoland/vscode_deno#727] opened 2022-10-07 10:09 UTC
**Describe the bug**

A new project created in a running vscode instance requires the restart of the language server (or restart of vscode) after initializing the workspace to work for vscode.

These two steps are required in its current form.
- open command palette and choose 'Deno: Initialize Workspace' to initialize the workspace.
- open command palette and choose 'Deno: Restart Language Server'.

[long discussion here](https://github.com/denoland/vscode_deno/issues/66#issuecomment-884711359) with no actual fix even after 2 years following it.

**To Reproduce**

- open a folder, preferred to be empty
- open folder in vscode
- open terminal and initialize a new project `deno init`
- open command palette and initialize the workspace
- open `main_test.ts` and see `cannot find name 'Deno'` error
- open command palette and restart the language server. the error is gone.

**Expected behavior**

after initializing the workspace, the extension should do its job without a user manually restarting the language server every single time a new project is created, including restarting the language server by self since it is a crucial step.

**Screenshots**

steps are clear to reproduce

**Versions**

vscode: 1.71.2
deno: 1.26
extension: 3.13.1

**Comment by kitsonk** [comment] 2022-10-09 05:33
I followed those steps exactly and cannot reproduce.  After opening `main_test.ts` this is what I see:

<img width="1020" alt="main_test_ts_—_blank_and_blank_—_-zsh_—_120×75_and_for_a_new_project__initializing_a_workspace_requires_a_restart_of_the_language_server_·_Issue__727_·_denoland_vscode_deno" src="https://user-images.githubusercontent.com/1282577/194739683-c349180d-cded-4a9e-96a8-24b1dfd1be70.png">

No errors or issues.

Can you please provide the output `deno --version`.  Also can you over over the "cannot find name 'Deno'" error message and provide the full text.  Specifically looking for the source of the diagnostic, it is from `deno-ts` or just `ts`.

> [long discussion here](https://github.com/denoland/vscode_deno/issues/66#issuecomment-884711359) with no actual fix even after 2 years following it.

There is no actual fix because in almost every case we could dig into, there were other environmental or configuration issues or the person with the issue could not help us dig deeper.

**Comment by yilmazdurmaz** [comment] 2022-10-09 07:30
I wish I had a video recording of it because it now is gone and the same step, as you said, does not work.

Have you tried this in VSCode v1.71.2? In the meantime, I updated VSCode to 1.72.0 and it might be affecting the issue because now the extension seems to start instantly. I tried its new "settings profile" to create an empty profile, but that too has no problem.

For this while, I don't have time to revert to 1.71.2 so we may close this issue thinking it was a problem from vscode, or keep it around a while and see if that happens again!?

`deno --version`
>deno 1.26.0 (release, x86_64-pc-windows-msvc)
>v8 10.7.193.3
>typescript 4.8.3

Error is nothing special, the one we get from the typescript language server before deno extension and language server take over the file format.
`Cannot find name 'Deno'.ts(2304)`

**Comment by kitsonk** [comment] 2022-10-09 11:36
```
Cannot find name 'Deno'. ts(2304)
```

This is coming from the built-in language server and feels like it might be an issue with our ability to mute built-in diagnostics.  We have had intermittent reports of it on Windows, especially if the users is running WSL.  Are you using vscode in a WSL enviornment?

**Comment by yilmazdurmaz** [comment] 2022-10-09 12:04
>Are you using vscode in a WSL enviornment?
Nope. I do have WSL but I haven't tried that yet. this problem comes from the windows environment.

**Comment by yilmazdurmaz** [comment] 2022-10-09 13:29
> This is coming from the built-in language server and feels like it might be an issue with our ability to mute built-in diagnostics.

Oh, I misunderstood that statement. So it might not be that deno language server was not working, but instead, both language servers were running on the same file. that makes sense.

**Comment by kitsonk** [comment] 2022-10-10 06:46
Yes, `ts(xxxx)` come from the built-in TypeScript language server in vscode, while `deno-ts(xxxx)` come from the TypeScript language server built into Deno.  When Deno is enabled `vscode_deno` send information to a Deno installed plugin to the built-in language server about what is Deno enabled in order to "mute" built-in diagnostics.

When the issue occurs, it is a failure in either the communication between vscode_deno and the plugin, or the plugin wasn't running, or the plugin couldn't mute the diagnostics.

In prior instances, running things under WSL on windows can change the shape of the file paths in a way that it becomes difficult for the plugin to "mute" Deno enabled diagnostics, which is why I asked about WSL.

If in cases where it occurs, using the _Deno: Restart Language Server_ corrects the issue, then it is likely that there is some sort of issue with the communication between `vscode_deno` and the plugin.  The "problem" is we rely upon vscode internal APIs to do the communication.  Hrmmmm....

**Comment by bartlomieju** [comment] 2023-07-11 00:04
I believe this issue is now fixed, feel free to reopen if you can still reproduce it.

**Closed by bartlomieju** 2023-07-11 00:04 UTC
Labels: needs investigation
