### ISSUE TITLE
LSP refuses to start

### ISSUE THREAD

**Issue by jcc10** [denoland/vscode_deno#392] opened 2021-04-15 05:18 UTC
### test
When starting VS code with a .ts file open, the language server fails to start.

**To Reproduce**

1. Open VS Code
2. Open .ts file
3. The following toasts pop up:  
a. ```Couldn't start client Deno Language Server```
b. ```A request has failed. See the output for more information.```
4. The output is as follows:
```
[Error - 10:12:09 PM] Starting client failed
Launching server using command deno failed.
```

**Expected behavior**

The LSP should just run.

**Versions**

vscode: 1.55.2
deno: ```1.9.0 (release, x86_64-unknown-linux-gnu)```
extension: v3.3.0 & Canary v0.0.10

```deno lsp``` runs in the vscode built-in terminal so I know that's installed correctly.

**Comment by kitsonk** [comment] 2021-04-15 05:29
What is the output of:

```
> which lsp
```

What specific operating system?

How did you install Deno?

Had it been working previously?

**Comment by jcc10** [comment] 2021-04-15 05:46
@kitsonk 
> What is the output of:
> 
> ```
> > which lsp
> ```

Nothing. I am going to go out on a limb and say that's the problem.

> What specific operating system?

Debian/Ubuntu/Pop!_Os

> How did you install Deno?

```curl -fsSL https://deno.land/x/install/install.sh | sh``` and have been upgrading ever since.

> Had it been working previously?

Yes, however I recently did a refresh of my OS. However I did a complete re-install of VS Code and presumed that deno lived in my home directory which was untouched.

**Comment by kitsonk** [comment] 2021-04-15 11:16
> Nothing. I am going to go out on a limb and say that's the problem.

Ooops... sorry...

```
> which deno
```

**Comment by jcc10** [comment] 2021-04-15 19:11
@kitsonk 

```
$ which deno
/home/digitalkitsune/.deno/bin/deno
```

**Comment by kitsonk** [comment] 2021-04-15 21:36
This isn't a fix, but does setting `"deno.path": "/home/digitalkitsune/.deno/bin/deno"` in your VScode resolve the issue?

**Comment by jcc10** [comment] 2021-04-15 21:56
Yes, I also didn't know that setting existed. Thanks for the temp fix.

I also just double checked and the bin folder is in my path.

**Comment by kitsonk** [comment] 2021-04-15 22:11
We have some other reports of this (on linux) and haven't been able to narrow down exactly why it doesn't work, though `deno` is clearly available in the path.  We are likely going to need to add more information to the error handling when we can't start.

**Comment by ross-weir** [comment] 2021-05-14 09:30
I ran into this issue and explicitly setting `deno.path` also fixed the problem.

Running a Windows 10 host OS with VSCode using Ubuntu WSL.

I'm wondering if it might have something to do with this: https://github.com/denoland/vscode_deno/blob/1fe0271591cadb95c773f26241ff5d59d9edb2b1/client/src/extension.ts#L358

Maybe it's detecting my host os platform and returning the windows path when running in WSL. I had a quick attempt at debugging but I'm not sure how to launch the extension dev host using WSL.

Hopefully this helps.

**Comment by shantaram3013** [comment] 2021-07-02 09:16
Hi, apologies for resurrecting an old thread, but has the `deno.path` setting been removed? I'm currently experiencing this issue, but neither setting the property in the global `settings.json` nor setting it in the workspace seems to work.

I get an error that looks like this:
![image](https://user-images.githubusercontent.com/22570968/124252088-3f3aa880-db44-11eb-93f9-a816a1143d49.png)

**Comment by kitsonk** [comment] 2021-07-19 23:42
> Hi, apologies for resurrecting an old thread, but has the `deno.path` setting been removed? I'm currently experiencing this issue, but neither setting the property in the global `settings.json` nor setting it in the workspace seems to work.

It hasn't been removed. What version of the extension do you have installed?

**Comment by shantaram3013** [comment] 2021-07-20 11:18
> It hasn't been removed. What version of the extension do you have installed?

I'm running the Canary v0.0.10 from the Open VSX marketplace.

**Comment by lucacasonato** [comment] 2021-07-20 11:23
@shantaram3013 Install this extension instead: https://open-vsx.org/extension/denoland/vscode-deno

**Comment by shantaram3013** [comment] 2021-07-20 11:47
Thanks a lot, that worked!

**Comment by nnmrts** [comment] 2021-11-20 07:38
Just wanted to report that I encountered this issue on macOS right now, so it doesn't seem to be a linux specific issue.

I installed deno with curl as well and deno gets added to the path by my zsh profile file, maybe that's the issue?

**Comment by SIMPalaxy** [comment] 2021-11-26 18:46
I had the same issue, and closing and reopening VSCode worked, but strangely reloading the window did not (which is what I was trying to do before to update it's access to the PATH variable. Seems like a problem on the part of VSCode.

**Comment by InSuperposition** [comment] 2021-12-09 17:28
I'm on OS X and adding [the path to VS Code settings](https://github.com/denoland/vscode_deno/issues/392#issuecomment-820746463) resolved the issue.

I'm see a similar issue when using a VS Code extension to format a commit message, which path could not find a path to `npx`. It was an issue with `nvm` and other version managers, [husky resolved the issue by adding a path to the user's `~/.huskyrc` file.](https://typicode.github.io/husky/#/?id=command-not-found)

**Comment by GerbenRampaart** [comment] 2021-12-30 12:18
For anyone being an idiot like I was: I had this error when I got my new dev machine and eagerly installed vscode and the extension and forgot to install Deno.

And then googling the error, ending up here and feeling a bit silly.

**Comment by Niek** [comment] 2022-01-20 10:16
For macOS Homebrew users: adding this to .vscode/settings.json fixed it for me:
`"deno.path": "/opt/homebrew/bin/deno"`

**Comment by kinghat** [comment] 2022-01-20 18:11
the deno install directions say:
> Manually add the directory to your $HOME/.bash_profile (or similar)
>   export DENO_INSTALL="/home/kinghat/.deno"
>   export PATH="$DENO_INSTALL/bin:$PATH"
but i think people are just manually installing to `.bashrc`(in my case on kde neon which is ubuntu based) and not to `.profile`, again which is what its called on my environment.
```sh
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
    PATH="$HOME/.local/bin:$PATH"
fi

export PATH="$HOME/.cargo/bin:$PATH"
# Ubuntu make installation of Ubuntu Make binary symlink
PATH=/home/kinghat/.local/share/umake/bin:$PATH

export DENO_INSTALL="/home/kinghat/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
```
what that fixed for me is the language server starting properly when opened in a simple deno dir in vscode. where it still fails is with vscode workspaces when opened directly via the `.code-workspace` file. if i open a fresh vscode session and then open the workspace via File -> Open Recents in the menu, the language server starts just fine for me.

so putting the directory in the correct location, in my `.profile` and not `.bashrc`, and also opening via Recents and not directly opening a `.code-workspace` file the issues are gone. maybe this is a bug in vscode? though, i dont have this issue with other language servers so :man_shrugging:

**Comment by Natetronn** [comment] 2022-01-26 20:32
I too am running into this issue when opening directly from .code-workspace.

**Comment by kinghat** [comment] 2022-01-26 20:34
> To confirm, I too am running into this issue when opening directly from .code-workspace.

does it work normally if you open from recent or `ctrl + r`?

**Comment by Natetronn** [comment] 2022-01-26 20:46
Now I'm not able to reproduce the error. I killed Deno process and even resortedd to restarting my PC to see if .code-workspace would have the same error again too, but it didn't. I'm not sure what the trigger is now, tbh. I can't seem to trigger the error on either method of opening a workspace. Of course, I did run into it, otherwise I wouldn't be here lol.

**Comment by mwoodpatrick** [comment] 2022-01-30 12:30
I'm running on latest WSL-2 and have a multiroom workspace and in the root directory in.vscode/settings.json I have

{
    "deno.enable": true,
    "deno.lint": true,
    "deno.unstable": true,
    "deno.path": "/home/mwoodpatrick/.deno/bin/deno"
}

but I'm still seeing this error

**Comment by GerbenRampaart** [comment] 2022-02-04 16:05
I have the same error on macos. two machines with a fresh install of vscode + deno + extension

**Comment by kitsonk** [comment] 2022-02-06 21:03
> what should the "deno lsp" command do I can't find much documentation on this, is there a way I can see if its working outside of vscode?

`deno lsp` starts a server that listens for requests on stdin and sends responses on stdout, so it really isn't designed to be humanly interactive.  In theory you could pipe something to it, and you should get an error message like this:

```
failed to decode message: missing required `Content-Length` header
Content-Length: 75

{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}%     
```

@dsherret any ideas about why it is failing with WSL2?

**Comment by bjesuiter** [comment] 2022-04-16 11:28
I had the same problem on macOS Monterey. 
I think the reason was that I installed deno with homebrew and the path now is: 
`/Users/bjesuiter/.homebrew/bin/deno`

This is in the path, but for some reason, the extension does not pick it up. 

Anyway, using the "deno.path" setting explicitely fixes the issue for me.

**Comment by gusparr28** [comment] 2022-06-16 02:29
> This isn't a fix, but does setting `"deno.path": "/home/digitalkitsune/.deno/bin/deno"` in your VScode resolve the issue?

This worked like a charm for me. This "fix" seems to be something that could be fixed from the core, however, for now, this is the best way to solve it.

**Comment by GerbenRampaart** [comment] 2022-06-16 08:12
> > This isn't a fix, but does setting `"deno.path": "/home/digitalkitsune/.deno/bin/deno"` in your VScode resolve the issue?
> 
> This worked like a charm for me. This "fix" seems to be something that could be fixed from the core, however, for now, this is the best way to solve it.

Still a problematic fix. You reference your own specific path in that settings.json, which other team members need to change because we generally like committing our settings.json to git. 

I don't quite grasp why I can fix the extension by placing the exact output from ''which deno" in deno.path in the settings.json but the extension can't reach the same conclusion.

**Comment by nayeemrmn** [comment] 2022-06-16 09:34
This might be a case of the VSCode extension host not using a login shell, therefore not loading `~/.bash_profile` (which the deno installer recommends) and having an incorrect `PATH`.

I used to have this problem on a previous machine and it affected both rust-analyzer (not finding `cargo`) and vscode_deno. On my current machine, I apparently added `"terminal.integrated.shellArgs.linux": ["-l"]` to address such an issue but it works without it now so I don't know.

@gusparr28 @GerbenRampaart Do you use `~/.bash_profile` to add deno to the `PATH`? If so, try moving that to `~/.bashrc` and see if it fixes the issue.

**Comment by nayeemrmn** [comment] 2022-06-16 10:06
> What's going on? I have only installed deno using the official shell script. It's not in my brew list (I didn't use brew to install it but I doublechecked). I've also never moved the executable or modified it's path in the zshrc. And I only upgrade using 'deno upgrade'.

If that's true I'm not sure how that would have gotten there. I'd say just delete `/usr/local/bin/deno`, run `deno upgrade` to bring the other one up to date and pretend it never happened

**Comment by gusparr28** [comment] 2022-06-16 12:52
> This might be a case of the VSCode extension host not using a login shell, therefore not loading `~/.bash_profile` (which the deno installer recommends) and having an incorrect `PATH`.
> 
> I used to have this problem on a previous machine and it affected both rust-analyzer (not finding `cargo`) and vscode_deno. On my current machine, I apparently added `"terminal.integrated.shellArgs.linux": ["-l"]` to address such an issue but it works without it now so I don't know.
> 
> @gusparr28 @GerbenRampaart Do you use `~/.bash_profile` to add deno to the `PATH`? If so, try moving that to `~/.bashrc` and see if it fixes the issue.

Yes, it worked for me when I moved to ~/.bashrc. But I keep saying, this isn't a nice way to solve the issue. There should be a solution coming from the core, as happens with Node.

**Comment by nayeemrmn** [comment] 2022-06-16 12:56
> Yes, it worked for me when I moved to ~/.bashrc. But I keep saying, this isn't a nice way to solve the issue. There should be a solution coming from the core, as happens with Node.

No it's completely out of band of the LSP -- we need to change `deno_install` to recommend `.bashrc` instead of `.bash_profile`. Otherwise it's a VSCode problem.

**Comment by gusparr28** [comment] 2022-06-16 13:02
> > Yes, it worked for me when I moved to ~/.bashrc. But I keep saying, this isn't a nice way to solve the issue. There should be a solution coming from the core, as happens with Node.
> 
> No it's completely out of band of the extension -- we need to change `deno_install` to recommend `.bashrc` instead of `.bash_profile`. Otherwise it's a VSCode problem.

and isn't there a way to automatically add the environment variables to ~/.bashrc when downloading deno instead doing manually?

**Closed** 2022-06-18 15:47 UTC
Labels: bug, needs investigation
