### ISSUE TITLE
VS Code variable renaming doesn't work in *new* workspaces when Deno plugin is enabled

### ISSUE THREAD

**Issue by jaredkrinke** [denoland/vscode_deno#585] opened 2021-11-30 22:26 UTC
**Describe the bug**
VS Code's F2/Ctrl+Shift+R rename for variables doesn't work in new workspaces when the Deno plugin is enabled. It works fine in TypeScript projects where I haven't enabled the Deno plugin.

**To Reproduce**

1. Create a **new** folder and open it in VS Code
2. Initialize the Deno plugin for the workspace
1. Create a new TypeScript file
2. Type some code, e.g. `const tmp = 5;`
3. Put the cursor on `tmp`
4. Hit F2 (or use Refactor -> rename from the right-click context menu)
5. Type in the new name

**Expected behavior**
The variable and all occurrences of the variable are renamed (this is what happens in projects where the Deno plugin hasn't been enabled).

**Actual behavior**
Nothing happens.

**Screenshots**
I can provide them, if needed.

**Versions**
Deno plugin version:
v3.9.2

VS Code versions:

Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by jdelarubia** [comment] 2021-12-01 17:41
I've been experiencing the same issues but I have been able to "fix" it by tweaking some vscode **workspace** settings.
Sample settings:
```json
{
    "deno.enable": true,
    "deno.path": "c:\\deno\\deno.exe",
    "deno.lint": true,
    "deno.internalDebug": true
}
```
Now, for this project, I can delete the `deno.path` or, disable `deno.lint` or `deno.internalDebug` and it keeps working. It seems to have picked up whatever, so I have no explanation for this.

**Comment by jaredkrinke** [comment] 2021-12-02 16:58
So... this just started working for me in Deno projects today. All my Deno, Deno plugin, and VS code versions are identical, but I did reboot my computer once in the meantime.

F2/rename had been consistently broken for me for at least a day when I opened this issue, but it's working now, so I'm going to close this issue to avoid distracting the Deno authors with something I can't even reproduce anymore.

@jdelarubia (or anyone else) if this still happens to you after a reboot, consider reopening the issue.

**Comment by jaredkrinke** [comment] 2021-12-06 04:47
This happened to me again today but restarting VS Code fixed it. I'm still not sure how I keep getting into this state.

**Comment by outloudvi** [comment] 2021-12-27 17:22
I can replicate this: renaming doesn't work for a workspace that was just created, but work after restarting VSCode. Not sure if this a problem at vscode_deno's side or VSCode's side, but the behavior seems to be reproducible.

**Comment by jaredkrinke** [comment] 2021-12-27 20:01
@outloudvi figured out that this happens when you open a new workspace and initialize it for Deno the first time. Updated title and steps to reflect this.

**Comment by martin-braun** [comment] 2022-03-10 21:52
For me refactoring in a workspace won't work at all, no matter if I restart VSCode or initialize Deno for the first time or not.

**Comment by chmac** [comment] 2022-03-13 16:21
I'm experiencing similar issues. When I export a const from one file, renaming in that file wouldn't work, but renaming from another file did successfully rename all instances, and after having done that, renaming in the original file now works. I also tried enabling / disabling the settings @jdelarubia shared above, can't say if this had an impact. Seems like an intermittent bug which will likely be hard to track down.

**Comment by smack0007** [comment] 2022-11-03 08:34
I had this problem in a project and it turned out that I had specified to use an import map that did not exist (copy and paste error from a different project). Deno was showing me a warning in a vscode popup window that I of course have ignored for several days. After removing the import map config value and restarting vscode Rename Variable started to work for me again.

**Comment by shinebayar-g** [comment] 2023-02-09 03:51
Wow just ran into this and had a mini heart attack. Rename function (F2) didn't rename the variables and failed silently. I reloaded the VSCode and it finally started worked again. 😌

**Comment by TheCymaera** [comment] 2023-02-10 15:33
Same issue. Fixed by reloading window (`> Developer: Reload Window`).

**Closed** 2023-03-30 21:47 UTC
Labels: bug, needs investigation
