### ISSUE TITLE
Auto-import fails to group item from the same file

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/vscode_deno#1062] opened 2024-02-04 19:38 UTC
I call auto-import to import 3 const from the same file and it prints out 3 imported line. I believe it is common idea to have 1 line for 1 file.

### Screenshots

![image](https://github.com/denoland/vscode_deno/assets/68631458/c911f333-c127-498a-b4de-ad2da15187ad)

### Versions

**vscode**

```
Version: 1.86.0
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:27:46.147Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-10022-tuxedo
```

**deno** 
```
deno 1.40.3 (release, x86_64-unknown-linux-gnu)
v8 12.1.285.6
typescript 5.3.3
```

**extension** `v3.33.3`

**Comment by nayeemrmn** [comment] 2024-10-11 05:39
I can't reproduce this currently. Closing for now, please comment here if it's still an issue.

**Closed by nayeemrmn** 2024-10-11 05:39 UTC
