### ISSUE TITLE
Shouldn't show errors for deno specific tsconfig options

### ISSUE THREAD

**Issue by bxantus** [denoland/vscode_deno#500] opened 2021-08-23 10:46 UTC
**Describe the bug**
I'm using some deno specific options in my `tsconfig.json`, like some [deno built-in libraries](
https://deno.land/manual@v1.13.1/typescript/configuration#using-the-quotlibquot-property).

It all works fine wirth deno, but vscode shows errors and warnings that the selected options are not valid.

The contents of my tsconfig.json:
```json
{
    "compilerOptions": {
        "jsx": "react",
        "jsxFactory": "h",
        "lib": ["dom", "esnext", "deno.ns", "deno.unstable"],
        "inlineSourceMap": true,
        "noImplicitAny": false
    }
}
```

And I receive the following errors:
```
Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'webworker.iterable', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2020.bigint', 'es2020.promise', 'es2020.sharedmemory', 'es2020.string', 'es2020.symbol.wellknown', 'es2020.intl', 'es2021.promise', 'es2021.string', 'es2021.weakref', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint', 'esnext.string', 'esnext.promise', 'esnext.weakref'.
Value is not accepted. Valid values: "ES5", "ES6", "ES2015", "ES2015.Collection", "ES2015.Core", "ES2015.Generator", "ES2015.Iterable", "ES2015.Promise", "ES2015.Proxy", "ES2015.Reflect", "ES2015.Symbol.WellKnown", "ES2015.Symbol", "ES2016", "ES2016.Array.Include", "ES2017", "ES2017.Intl", "ES2017.Object", "ES2017.SharedMemory", "ES2017.String", "ES2017.TypedArrays", "ES2018", "ES2018.AsyncGenerator", "ES2018.AsyncIterable", "ES2018.Intl", "ES2018.Promise", "ES2018.Regexp", "ES2019", "ES2019.Array", "ES2019.Object", "ES2019.String", "ES2019.Symbol", "ES2020", "ES2020.BigInt", "ES2020.Promise", "ES2020.String", "ES2020.Symbol.WellKnown", "ESNext", "ESNext.Array", "ESNext.AsyncIterable", "ESNext.BigInt", "ESNext.Intl", "ESNext.Promise", "ESNext.String", "ESNext.Symbol", "DOM", "DOM.Iterable", "ScriptHost", "WebWorker", "WebWorker.ImportScripts", "Webworker.Iterable", "ES7", "ES2021", "ES2020.SharedMemory", "ES2020.Intl", "ES2021.Promise", "ES2021.String", "ES2021.WeakRef", "ESNext.WeakRef".
```

Also I receive the above messages two times, both for deno.ns and for deno.unstable.

**To Reproduce**

1. Use a tsconfig.json with deno specific libraries

**Expected behavior**

No error messages for [deno built-in libraries](
https://deno.land/manual@v1.13.1/typescript/configuration#using-the-quotlibquot-property)

**Versions**
vscode: 1.59.1 deno: 1.13.1 extension: 3.8.0

**Comment by lucacasonato** [comment] 2021-08-23 10:47
Duplicate of https://github.com/denoland/vscode_deno/issues/326

**Closed by lucacasonato** 2021-08-23 10:47 UTC
