### ISSUE TITLE
Mixing Deno with (Non-Deno) TypeScript - Different File Extension for Deno?

### ISSUE THREAD

**Issue by hediet** [denoland/vscode_deno#408] opened 2021-05-02 10:51 UTC
Hi! Thanks for working on this awesome extension!

I am evaluating to use Deno for some build-scripts along a non-deno NodeJS + Browser TypeScript project. I like that it is very easy to bring in powerful and more importantly typed dependencies (unlike GitHub Actions, where there is no type system). This enables single-file scripts (without any package.json, tsconfig, node_modules, yarn.lock etc.).

However, it seems to me that the Deno language server and the TypeScript/JavaScript language server are mutually exclusive per project.
I guess this is due to both Deno and NodeJS files using the `*.ts` file extension.

What is you story for mixing Deno scripts with non-Deno TypeScript files?
Maybe it would be helpful if a custom file extension for Deno could be established.

**Comment by kitsonk** [comment] 2021-05-02 22:45
This is a duplicate of #314 and am currently working on resolving.

**Closed** 2021-05-02 22:45 UTC
Labels: duplicate
