### ISSUE TITLE
Deno inspector closes socket before vscode can connect

### ISSUE THREAD

**Issue by DanteMarshal** [denoland/vscode_deno#557] opened 2021-10-10 10:52 UTC
**Describe the bug**
Debugger only works once after reloading cache, Then exits with code 1 and next debug sessions don't work until the command `deno cache -r <file>` is ran.

**To Reproduce**

1. Create a simple typescript file, let's say `Hi.ts` with this code :   `console.log('Hi');`
2. Set a breakpoint
3. Launch Debugger using F5 (Without a launch.json file), The breakpoint hits. Once you end debugging and expect the program to end, the debugger controls just stay there; and you have to press stop to end the session.
4. At the end of the session you'll have an output similar to this one in console :  
```
B:\Prog\Dev\Deno\deno.EXE run --unstable --inspect --allow-all .\Hi.ts
Hi
Hi.ts:1
Debugger listening on ws://127.0.0.1:9229/ws/9e5ecde2-ab9f-41bf-aede-e8194a78d3d4
Check file:///B:/Proj/DenoIssue/Hi.ts
Debugger session started.
Process exited with code 1
```
5. Try to launch the debugger again without making any changes to the code.
6. The debugger doesn't work, VS Code debugging controls disappear and you'll end up with just this line as your output :  
```
B:\Prog\Dev\Deno\deno.EXE run --unstable --inspect --allow-all .\Hi.ts
```
7. Now run this command : `deno cache -r Hi.ts` to reload the cache.
8. Try to launch the debugger again, The same thing as step 3 happens, and the story continues !

**Expected behavior**
At step 3, process is expected to exit (with code 0) after debugging is finished.
At step 6, debugger is expected to work without the need to reload the cache.

**Screenshots**
Step 3 : Debugger Working
![Debugger Working](https://user-images.githubusercontent.com/17954172/136692221-b05d88db-a5d6-402c-bb2e-c5fc75fa699b.png)

Step 3 : End of Debugging, Program doesn't exit
![End of Debugging](https://user-images.githubusercontent.com/17954172/136692303-1508dadb-cd99-4034-98c7-be18cbb0b94a.png)

Step 4 : Process exiting with non-zero code after stopping the debugger using the controls' stop button.
![Process exiting with code 1](https://user-images.githubusercontent.com/17954172/136692315-d68e5dba-a8ed-4c70-bacd-be2d193e0413.png)

Step 6 : Trying to debug the same code again, results in unexpected behavior
![Trying to debug again](https://user-images.githubusercontent.com/17954172/136692361-3963ee18-d773-4277-876b-a0599fd90e8a.png)

**Versions**

VSCode :  
- Version: 1.61.0 (system setup)
- Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
- Date: 2021-10-07T18:13:09.652Z
- Electron: 13.5.1
- Chrome: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Windows_NT x64 10.0.19043

Deno :  
- deno 1.14.3 (release, x86_64-pc-windows-msvc)
- v8 9.4.146.19
- typescript 4.4.2

Extension :  3.9.1

**Comment by gm112** [comment] 2021-10-30 18:35
Just reporting in to say as of 10/28/2021, on Deno 1.15.3 Windows x64, this is still an issue. To reproduce, just simply trigger Deno with `--inspect` or `--inspect-brk` and it will just keep the debugging session open even if there are no further operations for the code to run. 

Not passing the inspect parameters is obviously a work around, or just force closing the debug session.

**Comment by MrSauna** [comment] 2021-12-05 20:10
As a tip for anyone just trying to get their homework done or something. Here's how I have managed to live with this issue. Put this in the beginning of the code 
```
const _sleep = async () => {
  await new Promise(resolve => setTimeout(resolve, 2000));
}
await _sleep();
```
At least for me debugging works as expected for the rest of the code after this snippet.

This is a extremely annoying issue as mostly beginners (me) will encounter this when running very simple scripts that run very fast. In practice once one gets a website running this isn't a issue anymore.

**Comment by bartlomieju** [comment] 2021-12-07 01:01
So I believe behavior for `--inspect` is correct in that it doesn't wait for debugger to connect and executes code immediately (as per https://github.com/denoland/deno/issues/12417#issuecomment-987454965); the crux of the issue seems to be https://github.com/denoland/deno/issues/9886

**Comment by bartlomieju** [comment] 2022-01-10 19:55
After further consideration I believe this issue is exactly the same as described by @kitsonk in https://github.com/denoland/deno/issues/12417#issuecomment-1000773654. It is expected behavior that `--inspect` does not wait for debugger to connect and if a program is only a single line `console.log` the execution finishes before the editor discovers and connects to the inspector (or Chrome Devtools for the matter). 

@MrSauna's solution is the preferred one, alternatively you can run with `--inspect-brk` instead to have enough time to connect to debugger and set up proper breakpoints.

@kitsonk I feel like this is "working as designed".

**Comment by kitsonk** [comment] 2022-01-10 19:58
Yes, as we have discovered, the same behaviour can be exhibited with other runtimes, like Node.js in vscode.

**Closed by kitsonk** 2022-01-10 19:58 UTC
Labels: working as designed
