### ISSUE TITLE
Deno language server seems to stop working after a while

### ISSUE THREAD

**Issue by applmak** [denoland/vscode_deno#403] opened 2021-04-26 15:07 UTC
After a while of use, the language server seems to stop working, and restarting it doesn't fix the issue. Errors & linter findings become stale, and don't update.

I'm unsure how this reproduces.

In the Output tab of the DLS process, I see:
```
Starting Deno language server...
  version: 1.9.1 (release, x86_64-apple-darwin)
Connected to "Visual Studio Code" 1.54.3
language server initialized
Server ready.
Received an undefined response from tsc for completion details.
Received an undefined response from tsc for completion details.
Received an undefined response from tsc for completion details.
Received an undefined response from tsc for completion details.
Received an undefined response from tsc for completion details.
Received an undefined response from tsc for completion details.
```

I'm not sure how to debug further.

**Versions**

vscode: 1.54.3
deno: 1.9.1
extension: 3.3.0

**Comment by kitsonk** [comment] 2021-04-26 21:49
I think it is a duplicate of denoland/deno#10368

**Closed by kitsonk** 2021-04-26 21:49 UTC
Labels: duplicate
