### ISSUE TITLE
Using a named export raises "module has no exported member" error in editor, but not in deno itself

### ISSUE THREAD

**Issue by ngruychev** [denoland/vscode_deno#414] opened 2021-05-14 15:15 UTC
### test

**Describe the bug**

When exporting a certain named export, the vscode extension shows an error that doesn't appear when actually running the file with deno. This error affects type completions in other files as well, making the imported type appear as `any`

**To Reproduce**

1. Place the following code in a .ts file:
`export type { AsTyped } from "https://cdn.skypack.dev/as-typed@1.3.0?dts";`
2. Place the following in .vscode/settings.json:
`{
  "deno.enable": true
}`
3. Wait for the following error to appear in vscode:
`Module '"https://cdn.skypack.dev/as-typed@1.3.0?dts"' has no exported member 'AsTyped'. Did you mean to use 'import AsTyped from "https://cdn.skypack.dev/as-typed@1.3.0?dts"' instead?`

**Expected behavior**

VSCode shows no errors
The module doesn't have a default export either, so the suggested fix doesn't work
Importing the module, and then exporting it again works for some reason, but it is not an ideal solution

**Screenshots**

![image](https://user-images.githubusercontent.com/8362100/118290959-b1e1bd00-b4df-11eb-996c-ceb4ff1166c1.png)

**Versions**

vscode: 1.55.2 deno: 1.10.1 extension: 3.4.0

**Comment by bradenmacdonald** [comment] 2021-07-12 16:54
I have run into what I think is the same bug, and have noticed something else: the error in VS Code goes away if you can open the source files involved in the editor.

For example, here is a small repository showing the bug: https://github.com/bradenmacdonald/deno-import-issues

If you open that folder in VS Code, you'll see this error:

<img width="1013" alt="Screen Shot 2021-07-12 at 9 47 32 AM" src="https://user-images.githubusercontent.com/945577/125325782-31301900-e2f6-11eb-8098-7b458a000bba.png">

For reference, the contents of `tests.ts` are:

```typescript
export * from "std/testing/asserts.ts";
```

But then if I open `tests.ts` file in the editor, the bug goes away:

<img width="863" alt="Screen Shot 2021-07-12 at 9 48 10 AM" src="https://user-images.githubusercontent.com/945577/125325858-49079d00-e2f6-11eb-8d32-531d417a7559.png">

If I close `tests.ts` again, the bug returns, either in the same form, or in a related form where it doesn't show an error (due to some caching I imagine) but it no longer has any type information for the imported `assert`:

<img width="701" alt="Screen Shot 2021-07-12 at 9 49 58 AM" src="https://user-images.githubusercontent.com/945577/125326102-866c2a80-e2f6-11eb-9cd3-d0f5b50fa016.png">


When I run into this bug in an actual project, I sometimes have to follow the import chain and open 3 or 4 different files, following the import statements manually, until the type errors in VS Code are resolved.

Deno 1.11.5, vscode_deno 3.7.0

I used import maps in the demo, since I was using them when I encountered this bug, but they may not be relevant.

**Comment by kitsonk** [comment] 2021-07-19 23:53
@ngruychev I opened denoland/deno#11458 as I have seen this problem when doing an `import type` from an import where there is types associated with a JavaScript file.

@bradenmacdonald I believe your issue is different, a duplicate of denoland/deno#11456

**Closed** 2021-07-22 05:00 UTC
Labels: bug
