### ISSUE TITLE
Installed Deno support for VSCode, but it did not work

### ISSUE THREAD

**Issue by chenguzhen87** [denoland/vscode_deno#62] opened 2020-05-27 17:54 UTC
![image](https://user-images.githubusercontent.com/28331609/83055111-faf9f080-a085-11ea-97ad-c501ef74e577.png)

**Comment by justjavac** [comment] 2020-05-28 00:40
title: **Installed Deno support for VSCode, but it did not work**

**Comment by makoven** [comment] 2020-05-28 01:47
@chenguzhen87 
Have you set the $DENO_INSTALL environment variable? Read carefully the note in the terminal immediately after the Deno installation script is completed: https://deno.land/#installation

**Comment by sharms** [comment] 2020-05-28 03:33
I have this issue also.  Set `$DENO_INSTALL` in `~/.profile`, `~/.zprofile` with no change in behavior.

**Comment by makoven** [comment] 2020-05-28 04:02
@sharms 
Will the Deno interpreter start if you write "deno" in the vscode builtin terminal?

**Comment by warwr1ck** [comment] 2020-05-28 04:37
i have the same isuue,too.
![image](https://user-images.githubusercontent.com/14226761/83099398-d7639400-a0df-11ea-82ad-d00f2071c417.png)

> @sharms
> Will the Deno interpreter start if you write "deno" in the vscode builtin terminal?
yes

**Comment by chenguzhen87** [comment] 2020-05-28 10:56
今天更新最到最新版本解决了
![image](https://user-images.githubusercontent.com/28331609/83133049-d862e880-a114-11ea-8374-1d24b6ded80a.png)

**Comment by sharms** [comment] 2020-05-28 14:25
Deno starts in the builtin terminal, however I believe that from a shell perspective it is interactive (reads from `.zshrc` or `.bashrc`), while VSCode reads its variables from `.profile` and `.zprofile` depending on the setup.

**Comment by makoven** [comment] 2020-05-28 14:59
It works for me on Ubuntu 20
```
# In ~/.profile
export DENO_INSTALL="/home/makoven/.deno"
PATH="$PATH:/share/node_modules/.bin:$DENO_INSTALL/bin"
```
```
# In the vscode terminal
$ echo $DENO_INSTALL 
/home/makoven/.deno
```
Nevertheless, I still can’t write something useful on Deno. There is no way to easily and automatically import types (as in Node/npm). And it's impossible to write portable code between Deno, Node and browser because of stupid import extensions (but this is more a problem of Node and Typescript devs, not Deno).

**Comment by towertop** [comment] 2020-06-01 06:04
Hi all, I might find the cause, latest VSCode 1.45.1 ship with inline tsc 3.8.3, while deno seems demand 3.9.x.

https://github.com/denoland/vscode_deno/issues/66#issuecomment-636628190

**Comment by David-Else** [comment] 2020-06-02 12:52
This extension works for me using built in 3.8.3, but if I change to use 3.9x it stops working and does not recognise `Deno` namespace.

**Comment by ry** [comment] 2020-06-06 20:29
Closed by https://github.com/denoland/vscode_deno/pull/77

**Closed by ry** 2020-06-06 20:29 UTC

**Comment by roflbofl322** [comment] 2021-02-25 05:29
I've had and old version of Deno. Akward, but just reinstall Deno and VSCode extension for it.

**Comment by nguyenquilong** [comment] 2022-10-12 02:40
In extension Deno, view tab details, there's help about use Deno for vsCode, 
`Open the VS Code command palette with Ctrl+Shift+P, and run the Deno: Initialize Workspace Configuration command.`
You need only enable , set it true.

**Comment by JNDEV0** [comment] 2022-10-19 03:53
> In extension Deno, view tab details, there's help about use Deno for vsCode, `Open the VS Code command palette with Ctrl+Shift+P, and run the Deno: Initialize Workspace Configuration command.` You need only enable , set it true.

This fixes it Thank you!

**Comment by iahmedgamal** [comment] 2025-01-02 20:49
> Initialize Workspace Configurati

this works as expected
