### ISSUE TITLE
import auto-complete is missing

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/vscode_deno#347] opened 2021-02-25 18:17 UTC
**Describe the bug**
Deno extension has lost all intellisense in recent update. Trying to import something is way more painful. Twice now i've just given up trying to code in deno because of this.

**To Reproduce**

1. try to import something from another file

**Expected behavior**

Intellisense should recommend auto-complete and auto-import

**Screenshots**

**Versions**

vscode: Latest
deno: deno 1.7.5 (release, x86_64-apple-darwin)
v8 9.0.123
typescript 4.1.4
extension: Latest

**Comment by lucacasonato** [comment] 2021-02-25 18:18
This is incorrect - only import intellisense is missing. All other completions are there as expected.

**Comment by Skillz4Killz** [comment] 2021-02-25 18:43
@lucacasonato Although I do agree intellisense is missing, I believe the issue goes farther than that.

There are several times now I have seen something like the following happen:

It seems to think that token of type string does not exist in this interface
![image](https://user-images.githubusercontent.com/23035000/109201087-684ec500-776f-11eb-862a-3c9c26a2565e.png)

But when you click on it and jump to it, you will see it does exist
![image](https://user-images.githubusercontent.com/23035000/109201107-6c7ae280-776f-11eb-84c9-afe16df6600b.png)
![image](https://user-images.githubusercontent.com/23035000/109201140-78ff3b00-776f-11eb-8340-fdc7b014c9ad.png)

**Comment by lucacasonato** [comment] 2021-02-25 18:49
So you are saying you see errors that you do not get when running the program with `deno run`? In that case, could you explain in what case this can be reproduced?

**Comment by Skillz4Killz** [comment] 2021-02-25 19:02
Exactly, when I ran it there are no issues. The weird thing is once i reload the VSC, the error warning disappears and it detects it properly.

**Comment by Skillz4Killz** [comment] 2021-02-25 20:54
Another instance
![image](https://user-images.githubusercontent.com/23035000/109215801-ab199880-7781-11eb-934a-1ddf7da2f127.png)

After reload:
![image](https://user-images.githubusercontent.com/23035000/109215817-b240a680-7781-11eb-8d0c-8604be7876b5.png)


Still not sure how to replicate this, it just randomly happens as I am coding

**Comment by Skillz4Killz** [comment] 2021-04-12 04:42
![image](https://user-images.githubusercontent.com/23035000/114341512-f61c1f00-9b27-11eb-8ad4-a3b250eff58f.png)

It knows the type as u can see at the top but it renders it as an error

**Comment by KatrinaKitten** [comment] 2021-04-24 04:44
I can second this issue, at least for import autocomplete. I now have to manually create and edit imports, where before Intellisense would allow me to begin typing an exported symbol from elsewhere in the project and autocomplete both the symbol itself and the proper import declaration for it.

**Versions**
vscode: 1.55.2
deno 1.9.1 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.5
typescript 4.2.2
extension 3.3.0

**Comment by kitsonk** [comment] 2021-07-19 23:30
This issue is conflating a few things.  I believe the root cause though is the use of import maps.  Even though this was opened earlier, I am going to mark this as a duplicate of duplicate of denoland/deno#11456.

**Closed** 2021-07-19 23:30 UTC

**Comment by Skillz4Killz** [comment] 2021-07-25 15:50
@kitsonk There are no import maps being used ever. It is an unstable feature and i avoid unstable whenever possible.

**Comment by justinsilvestre** [comment] 2022-02-06 09:48
@kitsonk I believe this issue was closed by accident. My import intellisense is broken, and I have no import maps configured.

Small repo reproducing the issue: https://github.com/justinsilvestre/deno_vscode_import_intellisense

My language server settings confirm that **no import map is configured**.

```json
{
  "enable": true,
  "cache": null,
  "certificateStores": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": false,
    "references": false,
    "referencesAllFunctions": false,
    "test": true
  },
  "internalDebug": false,
  "lint": true,
  "suggest": {
    "completeFunctionCalls": false,
    "names": true,
    "paths": true,
    "autoImports": true,
    "imports": {
      "autoDiscover": true,
      "hosts": {
        "https://deno.land": true,
        "https://x.nest.land": true,
        "https://crux.land": true
      }
    }
  },
  "tlsCertificate": null,
  "unsafelyIgnoreCertificateErrors": null,
  "unstable": false
}
```

OP also mentioned that they were using no import maps.

**Comment by kitsonk** [comment] 2022-02-06 20:39
It was not closed by accident.  There are a few different issues discussed here, none of them actionable.  If you think you are still experiencing an issue, open a new issue with the above information plus also the version of Deno and VSCode you are using.
