### ISSUE TITLE
Support for `deno.disablePaths` option.

### ISSUE THREAD

**Issue by Mqxx** [denoland/vscode_deno#906] opened 2023-09-05 08:26 UTC
**Is your feature request related to a problem? Please describe.**

When building a Deno module I have multiple files in the root of the directory. Some of them are Deno specific and others are for the frontend. In my `.vscode/settings.json` I have this configuration:

```json
{
    "deno.enable": true,
    "deno.unstable": true,
    "deno.enablePaths": [
        "./src",
        "./test",
        "./some/other/path"
    ]
}
```

I would like to be able to disable Deno also for specific files/paths.

**Describe the solution you'd like**

For example I would like to see support for a configuration like this:

```jsonc
{
    "deno.enable": true,
    "deno.unstable": true,
    // explicitly enable Deno for the following paths:
    "deno.enablePaths": [
        "./src",
        "./test",
        "./mod.ts",
        "./path/to/an/other/file.ts"
    ],
    // explicitly disable Deno for the following paths:
    "deno.disablePaths": [
        "./src/client",
        "./src/index.js"
    ]
}
```

Thanks for consideration. 😃

**Comment by bartlomieju** [comment] 2023-09-05 10:12
CC @nayeemrmn

**Comment by nayeemrmn** [comment] 2023-09-05 13:20
> For example I would like to see support for a configuration like this:
> 
> ```json
> {
>     "deno.enable": true,
>     "deno.unstable": true,
>     "deno.enablePaths": [
>         "./src",
>         "./test",
>         "./mod.ts",
>         "./path/to/an/other/file.ts"
>     ]
> }
> ```

This should already work, `enablePaths` has natural support for files. Can you check again?

Also see https://github.com/denoland/vscode_deno/issues/817.

**Comment by Mqxx** [comment] 2023-09-05 13:34
Hmm strange now it works... I don't know why it did not work in my last project... But thanks for the response and confirmation. 😅

**Comment by nayeemrmn** [comment] 2023-09-05 13:39
Closing as duplicate of #817.

**Closed by nayeemrmn** 2023-09-05 13:39 UTC
